keymap/vim.js
test/vim_test.js

In vim only cw is handled in a special way, other motions like ct c$ or cge do not exclude trailing whitespace

[vim] fix ct command

---

keymap/vim.js

The way I initially set it up to get the mode name did not report the mimetype form of CodeMirror's "mode" option (e.g. `text/x-csrc` as opposed to `clike`), so if `:set ft?` showed "clike" and you passed that same value into `:set ft=clike`, the extra C hooks would not be loaded. (Discussed in #3196.)

Fix bug showing imprecise value of vim 'filetype' option for mimetypes

---

keymap/vim.js

- Use 'unshift' instead of 'push' to ensure newly mapped commands come first (and hence take precedence over previously mapped commands)

[vim] ensure newly mapped commands take precedence

---

addon/mode/multiplex.js
addon/mode/multiplex_test.js
doc/manual.html

This simple change adds extra `open` and `close` token styles to multiplexing delimiters when `delimStyle` is set. This makes it easy to style open and close delimiter tokens as in this example:
For example, if `delimStyle` is set to `delim`, then the opening delimiter gets the following token styles: `cm-delim` and `cm-delim-open` and the closing delimiter gets `cm-delim` and `cm-delim-close`.

Multiplex addon: Add open and close tokens when highlighting delimiters

---

theme/dracula.css

This prevents selections from inheriting the default `#d9d9d9` background when editor is defocused.
reproducible @ https://codemirror.net/demo/theme.html#dracula

[dracula theme] consistent selection styling regardless of focus

---

src/util/bidi.js

As pointed out in mozilla/pdf.js#7844 by @timvandermeij. Maybe we should pull this into a shared module?

Correct bidi types for remaining Arabic chars

---

lib/codemirror.css

Ligatures were disabled in #3899 since some editors didn’t allow placing the cursor inside of them.
“Contextual alternatives” on the other hand still allow this, therefore this commit enables them to support e.g. Fira Code’s main gimmick.

CSS: Allow contextual glyph alternatives

---

mode/javascript/test.js

Hi, line like this in my code breaks parsing:
```
findById: (userId: number) => Promise<Array<{ id, name }>>;
```
Because `<` is parsed twice as a single operator but `>>` is parsed as one operator instead of two `>` ones. Putting space between `>>` fixes the issue, but that's not how the code is usually written.
I've added a failing test-case too.

TypeScript: double >> breaks parsing

---

mode/soy/soy.js
mode/soy/test.js

I got too eager with #4474; forgot to add tests.
The behaviour on https://codemirror.net/ is just as #4468 described:
The situation improved after #4474, but didn't take into account the greedy nature of the parser. The regex only examined parts of the words at a time and only the latter `\b` had any effect, meaning that words ending with a keyword would have that incorrectly highlighted:
With these changes, we grab the whole word at once and _then_ check to see if it is in fact a keyword:

[soy mode] Add tests for 9fe2053, find bug and fix it

---

mode/javascript/test.js

Test contains a valid TypeScript code:
```
const hello: {
prop1?: string;
prop2?: string;
} = {};
```
Right now the test fails because prop2 gets evaluated as variable instead of property. The definition should mirror interface syntax. If this is valid:
```
interface Hello {
prop1?: string;
prop2?: string;
}
```
then this is also valid:
```
const hello1: Hello = {};
const hello2: {
prop1?: string;
prop2?: string;
} = {};
```

TypeScript: add a test for usage of interface syntax with const

---

src/line/spans.js

Subtract by 3 to account for the 2 extra parameters for splice and for replacing an existing part.
I ran the tests for both master and my branch. There were failing tests, but the same for both branches.
I also ran bin/lint, but it seemed to already be upset with some other syntax ('let' to be exact). Since my changes are so small, I thought not to worry about it.
Let me know if there is something I am leaving out. Thanks!
Issue: #4582

Updated offset for removeReadOnlyRanges

---

mode/javascript/test.js

following code is parsed incorrectly, because of index signature (it can be seen for example here https://www.typescriptlang.org/docs/handbook/interfaces.html)
```
interface A {
[prop: string]: any;
prop1: any;
}
```
`prop1` is currently parsed as a `variable` instead as a `property`

TypeScript: broken when index signature is used

---

addon/search/search.js

At present it is impossible to style the label of the search dialog without affecting the other elements also.  For instance, if I want to position the buttons to the right and the label to the left, I cannot do this, even with flex box, as CSS doesn't let me target a text node.
Adding a wrapping element around the label text allows them to be styled easily without changing any existing functionality.

Added wrapping span to search dialog labels to make them easier to style

---

doc/realworld.html

The URL for the official blog has changed
Also, there has been a terminology change in the Blogger interface, now 'template' has been replaced by 'theme'

[real world uses] Update Blogger

---

addon/search/searchcursor.js

Hi
Fixed a misplaced semicolon in the searchcursor.js that was causing some parsing problems.
Thanks for your awesome work!
Cumps

Fix misplaced semicolon in searchcursor.js

---

addon/search/searchcursor.js
test/search_test.js

This prevents the test case search_expandingCaseFold from hanging in
Firefox 54 on Linux. Also enables the test in phantom.

[search] Apply normalization in adjustPos, too

---

src/display/scrolling.js
test/scroll_test.js

This way, only one char's left and right edges are used, instead of its
(logical) neighbour's right edges.
In bidi content, this avoids trying to scroll to two logically close,
but visually far apart positions in some situations.
Refer to #2254 for the original reason for this code.

Use cursor stickiness in ensureCursorVisible

---

doc/manual.html
src/edit/methods.js

This PR makes it possible for users to call `startOperation` and `endOperation` to batch changes that occur asynchronously. It also adds docs for those methods making clear that they are not for normal use cases and require some care. ([As discussed in this Discuss thread](https://discuss.codemirror.net/t/expose-startoperation-and-endoperation/1301/2))

Expose startOperation/endOperation in CodeMirror API.

---

addon/lint/lint.js

This is opt-in, the plugin needs to produce message_html instead of
message to be rendered as HTML.
We were using this with custom patch at phpMyAdmin, but I think it's better to integrate such feature upstream.

[lint plugins] Allow lint plugins to output HTML formatted messages

---

mode/d/d.js

The D mode for CodeMirror currently doesn't work well with [nested comments](http://dlang.org/spec/lex.html#comment).
Example
------------
```d
/+
I am a fancy string
+/
void main(){}
```
Try the following e.g. [here](http://codemirror.net/mode/d/index.html) - The entire text will be highlighted as comment.
See also:
- https://github.com/dlang-tour/core/pull/607
- http://dlang.org/spec/lex.html#comment
I have already applied this fix for run.dlang.io and put it in the merge queue. It should appear at e.g. https://run.dlang.io/gist/ddccbc1c0bf3ea9fb5723f1ccb9c3e42?compiler=dmd soon.

D Mode: Fix nested comments

---

mode/markdown/markdown.js
mode/markdown/test.js

Semi-fixes https://github.com/codemirror/CodeMirror/issues/4151 where fencedBlock in blockquotes was badly styled and lists leaked outside.
This is not a CM-compliant fix but is better than the previous buggy behavior.
Sometimes in the future I may look into making it CM-compliant (i.e. properly allow lists and codeBlocks inside blockquotes).

[markdown mode] disallow lists and fencedCode inside blockquote

---

mode/asciiarmor/asciiarmor.js
mode/asciiarmor/index.html
mode/coffeescript/coffeescript.js
mode/coffeescript/index.html
mode/meta.js
mode/shell/index.html
mode/shell/shell.js

Found a few more useful additions.
Most of these findings are from using the https://github.com/jshttp/mime-db/ project which attempts to aggregate the IANA, Apache, and nginx type lists.
I've not made it through their whole JSON file (yet! :wink:):
https://github.com/jshttp/mime-db/blob/master/db.json
I'll send a few more of these (most likely) as I trip over ones I need. Hope that's OK!
Tnx!
🎩

Add additional MIME types

---

mode/gfm/gfm.js
mode/gfm/index.html
mode/gfm/test.js
mode/markdown/index.html
mode/markdown/markdown.js
mode/markdown/test.js

- __commit 1__ - _support fencedCodeBlocks in base markdown as per CommonMark_
- Base markdown first-class support.
- Aligned with CommonMark, thus not disable-able nor customizable `fenceChars`.
- Moved fencedCode tests to `markdown/test.js` with minor tweaks.
- Updated doc, (auto) removed trailing whitespace so a bit mess there.
- Thought I'd simplify `gfm.js` after this change, but it turns out that's not yet easily possible.
- __commit 2__ - _allow to disable xml and fencedCodeBlock highlighting_
- Added `xml` option to disable inline xml highlighting. This is a good idea to support when one doesn't want to support HTML for security reasons, while want to retain ability to highlight xml in fenced code blocks.
- Added `fencedCodeBlockHighlighting` to enable previous behavior of not …

[markdown mode] meta stuff

---

keymap/vim.js

Fixed `Ctrl-W` vim's keybinding.
`∎` - cursor
Line: `hello/world∎`
Before:
Pressing `Ctrl-W` in insert mode makes:
```
hello∎/
```
After:
Pressing `Ctrl-W` in insert mode makes:
```
hello/∎
```

[vim bindings] fix vim emulation ctrl-w behavior #4931

---

mode/markdown/index.html

Adding documentation for the `allowAtxHeaderWithoutSpace` configuration parameter.

Documenting allowAtxHeaderWithoutSpace

---

mode/markdown/index.html

When submitting the previous commit, I had not noticed that the parameter allowAtxHeaderWithoutSpace had type Object instead of type boolean. I've fixed this now.

Fixed wrong type for allowAtxHeaderWithoutSpace

---

addon/edit/continuelist.js

Fixes this issue in continuelist addon:

[continuelist addon] Don't continue list when cursor is before bullet

---

keymap/vim.js

Happened if you entered visual block mode in one editor and then tried to exit insert mode in another, since lastChange comes from vimGlobalState.

[vim] Fix crash on exiting insert mode.

---

mode/meta.js

The language is named "Objective-C" rather than "Objective C".
Reference:
https://en.wikipedia.org/wiki/Objective-C

[languages] Fix the name of Objective-C 📛

---

mode/stylus/stylus.js

Instead of alternation groups that match in descending lengths I've used `\b` and progressive matching.

[stylus mode] parse CSS4 hex colors - #RGBA and #RRGGBBAA

---

src/input/keymap.js
src/input/keynames.js

* Changed: keyCode `3` -> <kbd>Pause</kbd>
<kbd>Pause</kbd> with <kbd>Ctrl</kbd> modifier produces keyCode `3`, which was set to `Enter` (why?). See also [MDN](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/keyCode
):
>"Pause" key with Control causes 0x03 (3).
* Added: keyCode `145` -> <kbd>ScrollLock</kbd>
Note: Ctrl-ScrollLock has keyCode 3, same as Ctrl-Pause, so I use event.code when available (Chrome 48+, FF 38+, Safari 10.1+)

Recognize ScrollLock and Pause with Ctrl modifier

---

mode/meta.js

`mime` property should be `mimes` because it's an array

[php mode] Fix invalid mime definition

---

demo/lint.html

As of 1d5c828f8348b7384cb38568f0d12075fd41917e the missing js semicolon is a warning and not an error anymore, therefore I added an error elsewhere.

[lint demo] Added JS error

---

mode/meta.js

[Handlebars](http://handlebarsjs.com/) is a template language primarily used for HTML which renders pretty well in `htmlmixed` mode, so I added its extensions to the `htmlmixed` mode.

[mode/meta] Add handlebars extensions to htmlmixed

---

addon/edit/matchbrackets.js

This fixes https://github.com/codemirror/CodeMirror/issues/5211 by storing the `currentlyHighlighted` variable on the instance of CodeMirror itself. I am unsure if `state` is the best spot to store the reference.

Fix matchBrackets to work with multiple cm instances

---

keymap/sublime.js

In addCursorToSelection, keep the cursor's position after short lines. For example (# is the cursor's position):
```
int main() {
#int x = 0;   // <--- Start with a cursor here.
#int y = 0;
#
#return 0;
}
```
instead of the current behavior:
```
int main() {
#int x = 0;   // <--- Start with a cursor here.
#int y = 0;
#
}
```
This is similar to [this pull request](https://github.com/codemirror/CodeMirror/pull/5207), but the behavior is more similar to Sublime's behavior.

[sublime keymap] Fix addCursorToSelection.

---

mode/stex/stex.js
mode/stex/test.js

Add support for inline math in LaTeX-style:
```tex
This is an equation \( E=mc^2 \), named after Einstein.
```

[stex mode] LaTeX-style inline math delimiters \( \)

---

mode/stex/stex.js
mode/stex/test.js

If you declare a `\label` and then want to make a `\ref` to it, you must literally repeat the argument of `\label` tag as the argument of `\ref` tag. So, the arguments are always `atom`s, even if they contain digits, underscores, colons etc.

[stex mode] Added some tags whose arguments are atom

---

mode/haskell/haskell.js

As of GHC 7.10 these are in the Prelude.

[haskell mode] Add "Applicative" and "*>" and "<*"

---

mode/meta.js

In my experience, `.tex` is a much more common extension for LaTeX documents.

Add "tex" to list of extensions for LaTeX mode.

---

mode/clike/clike.js

CodeMirror C and C++ currently highlight the string "null", which isn't defined in C/C++. Those languages do macro "NULL", though.

Highlight NULL instead of null in C/C++

---

mode/javascript/javascript.js
mode/javascript/test.js

Adds support for dynamic import syntax to the JavaScript mode. Currently this isn't handled, so, for instance, property access from dynamic imports - like
```js
import('foo').then(() => {});
```
Highlights `then` as a `variable`, not a `property`.
This PR allows for dynamic imports at the top level by detecting `(`, and handles imports in expressions by just continuing to the expression mode when they're detected.

Add support for dynamic import operator to JavaScript mode

---

addon/lint/javascript-lint.js

Setting error severity to "error" by default when there is no error.code property (#5260)

[javascript-lint] JSHINT backward compatibility (#5260)

---

mode/javascript/javascript.js
mode/javascript/test.js

[asynchronous iteration](http://2ality.com/2016/10/asynchronous-iteration.html) is a stage 4 ("finished") feature in ES2018, and its additional syntax - for await loops - don't require too much change in CodeMirror's JavaScript mode for support. All this PR does is it tolerates an `await` keyword between `for` and `(` - previously the await would cause the mode to drop out of `forspec` and fail to highlight the def/check/increment correctly.

Support for await syntax in JavaScript mode

---

mode/velocity/velocity.js

It is introduced dash in regexp for variables
#5287

[BUGFIX] Velocity variables with dash are not well highlighted #5287

---

addon/mode/multiplex.js

Some modes may return `CodeMirror.Pass` from their `indent` methods, which in the current code can get fed into the start state of another mode and mess things up. Fixed to check for this case.

Fix bug with indentation in multiplex.js

---

src/edit/mouse_events.js

If the CodeMirror script is being run in a different document than the CodeMirror instance itself, some mouse events will be sent to the wrong document. In particular mouse move is sent to `document` rather than the editor's document, which causes selection to break.
This pull request fixes that issue allowing instances of CodeMirror to be run in different documents than the script itself. 
To get code mirror to run in different documents you need to do something like:
```javascript
var editor = CodeMirror.fromTextArea(window.frames["iframe"].document.getElementById("code"), {
lineNumbers: true,
lineWrapping: true
});
```
We're specifically using this technique for some upcoming changes to our [RunKit Embeds](https://runkit.com/docs/embed). We load our main app in a background frame, …

Fix for some mouse events being sent to the wrong document

---

addon/merge/merge.css
addon/merge/merge.js

Primary motivation was to remove the use of `innerHTML` because the
Firefox extension validator raises a warning about this.
The obvious solution is to use `textContent` instead of `innerHTML`
but I thought it could be useful to have the ability to pick a
custom visual for the scroll-lock icon.
As per MDN documentation, all the supported browsers as per
CodeMirror documentation support `:after`.

[merge addon] Use CSS :after to style scroll-lock icon

---

addon/hint/javascript-hint.js

When using the editor in "application/json" mode, the standard javascript autocompletion would show up once triggered. Although it's deactivated by default and doesn't make sense to enable autocompletion in JSON mode on its own, this change fixes incorrect completions once you combine the default completion with your own custom logic.

[javascript-hint addon] Disable completion in json mode

---

addon/merge/merge.js

The merge view will incorrectly show a "Revert chunk" arrow when the text on both sides of the view are the empty string.
The getChunks() helper is not prepared to deal with an empty diff array.
The getDiff() helper returns an empty diff array when both strings to compare are empty, as the only diff item returned by diff_match_patch, `[0, ""]`, is removed as a result of the diff entry containing an empty string.
The chosen (trivial) fix is to simply check for the empty diff array case at the top of getChunks().
You can save the following HTML code in an `index.html` file to see the issue -- there are three MergeViews, the top one is the one showing the issue:
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1"> …

[merge addon] edge case arising when diff'ing two empty strings

---

mode/index.html

Currently I see 404 on [Language modes](https://codemirror.net/mode/index.html) when I click on [kotlin](https://codemirror.net/mode/kotlin/index.html)

404 on languages modes page

---

src/input/ContentEditableInput.js

There is a problem with Korean IME in the contenteditable mode, where `space` key will clear the current composition. As demonstrated here: (Key strokes: 'g', 'k', 's', 'r', 'm', 'f', SPACE in Qwerty layout)
This is caused by the `keypress` event. `keypress` should not happen during IME composition ([as spec](https://www.w3.org/TR/uievents/#keys-IME) + [ref](https://lists.w3.org/Archives/Public/www-dom/2011JulSep/0132.html)), but it does on Windows and Ubuntu for Korean IMEs, not for Chinese and Japanese IME, or anything on Mac. 
This PR fixes it by returning the keypress event if composing. Fixed behavior:

Fix space key clearing composition with Korean IME in contenteditable mode

---

mode/python/python.js

d0b1500 was a brilliant way to support nested f-string! This patch removes the original comments that do not apply any more.

Remove incorrect comment on nested f-string

---

keymap/vim.js
test/vim_test.js

I implemented this to replicate the traditional VIM keybinding. See the gif below for a demonstration of some of the edge cases.
I'm new to javascript, so any suggestions on cleaning it up are welcome.

Added vim keybinds for '(' and ')' in order to allow movement by sentences.

---

addon/hint/sql-hint.js
test/sql-hint-test.js

By adding classes that clearly define when a hint is a table or a keyword, it gives developers easy control if they wish to style hints differently. For example, you may wish to style table hints in a different colour to keywords (to make them easier to distinguish).

Add semantic classes to different types of SQL hints.

---

addon/lint/json-lint.js

Jsonlint exports in two different ways ->
One way is as an object of which parseError is a property, and another in which jsonlint = { parser: { ... parse, parseError }}
This should fix the issue s.t. people can require directly from jsonlint as a package.

For jsonlint package, make lint addon look at parser property of jsonlint.

---

src/input/ContentEditableInput.js

When using IME in `lineWrapping` + `contentEdtiable` mode, typing CJK characters puts the cursor at the wrong position. Steps to reproduce:
1. With existing text like:
```
- 123
- 456
```
2. Type Chinese characters at the end of Line 1 `123` with an IME (example: "台灣" with Zhuyin that is `w` `9` `6` `j` `0` `(space)`, `(enter)`)
3. See the cursor is put on the next line (after a `&nbsp;`). 
This problem only exist when the next line has `&nbsp;` created by `splitSpaces`
https://github.com/codemirror/CodeMirror/blob/9ed217d5b46f98581b7b751758686c5a70ad05d1/src/line/line_data.js#L192-L203
After composition ends & `pollContent`, the `&nbsp;` created to split spaces becomes real content, which I believe causes miscalculation of the cursor position.
This PR replaces nbsp with regular spaces in …

Fix nbsp (for space splitting) getting added as real spaces (contentEdtiable mode)

---

addon/hint/show-hint.js

Fixes show-hint selecting for initially unselected hints specified with option  `selectedHint: -1`

Fix show-hint selecting for initially unselected hints. #5380

---

src/input/ContentEditableInput.js

Line breaks disappear when pasting plain text from nodepad/textarea/command prompt in IE11 in `contentEditable` mode.
Specifically, this is because in `domTextBetween` a `fromNode` like`<span cm-text="">1<br>2<br>3<br>4<br>5</span>` is handled with `addText(node.textContent); return`, ignoring the `<br>`s inside.
This PR does a few things:
- only `addText` & `return` if `cm-text` has value
- otherwise walk the child nodes
- treat `br` along with `table`, `li` as blocks
- ignore empty elements (except for `br` which should be empty) to avoid unnecessary line breaks
- add extra line breaks for `p` and `pre`
FWIW this issue reportedly is also on archlinux/debian in Firefox 52/58, but I have yet been able to reproduce them.
---
As far as I can see changes to this method effects IME input in …

Fix line break disappearing with pasted text in IE11 under contentEditable mode

---

addon/dialog/dialog.js

Thanks for considering my other PR about adding insertBefore to the dialog. I think this approach is less invasive to the existing dom structure and allows for styling like this to avoid the dialog covering up the first few lines of text in the editor.
```
.dialog-opened .CodeMirror-scroll {
margin-top: 40px;
}
```
An advantage I see with this is it gives the application an indication of when a dialog is opened, allowing for many styling opportunities.

'dialog-opened' class when dialog is triggered

---

mode/markdown/markdown.js
src/util/StringStream.js

With some inputs, especially when they contain long lines with many whitespace characters, `stream.match(/ +$/, false)` in the Markdown mode gets terribly slow. In our case, it could lock up the editor for 10s of seconds.
~~As a quick fix, I added a method `StringStream.matchTrailing(character)` which replicates the behavior of `StringStream.match()` for the special case of checking for specific trailing characters.~~
I changed the regex to `^ +$` which improves the performance a lot.
* All tests pass
* No complaints from `bin/lint`

Replace stream.match(/ +$/, false) with a more efficient regex

---

theme/monokai.css

This makes the brightness of the tokens within the comment more similar to the rest of the comment block.

[monokai] Reduce the saturation of colors within doccomments

---

doc/manual.html

Exists since #4624 but wasn't documented in manual, only in demo.
(BTW thanks for the hard work it took to land that :heart:)
I tried to make the description useful to someone not familiar with bidi coding for multi-lingual users.  Not sure if too "preachy", but IMHO as long as CodeMirror doesn't autodetect per-line direction, it's good advice — editing with oppossite direction is significantly awkward, and letting users flip the whole editor is the best mitigation currently possible.
- I thought I should also clarify how `rtlMoveVisually` affects Home/End keys, and how it interacts with `direction` — but turns out it doesn't (at least not as I expected) :grin:  I need to study it better before proposing/implementing any improvement there...
Meanwhile, current description …

Document `direction` option

---

mode/markdown/markdown.js

Adds HTML comment support to the Markdown mode.
HTML comments are generally permissible in Markdown, per https://spec.commonmark.org/0.28/.

Add HTML commenting to markdown.js.

---

src/line/line_data.js

Ref #1362.
Firefox now also collapses spaces at the end of the line (tested on 62.0).
It should be harmless for any other browsers.

Prevent collapsing trailing spaces ("split spaces") on all browsers

---

mode/mllike/mllike.js

This provides default `hintWords` when auto-completing in OCaml or F# code.

[mllike mode] Provide `hintWords`

---

mode/clojure/clojure.js
mode/clojure/index.html
mode/clojure/test.js
test/index.html

Besides adding tests, this PR also fixes a few minor issues revealed by the tests:
- Keywords or numbers following a single quote (`'`) were being styled as `variable` instead of `atom` or `number`, respectively.
- Single quote (`'`) was missing on the list of valid symbol characters. Such symbols include `+'`, `*'` and, `-'`.
- `new` and `when-some` were missing on the keyword list. There are a few other symbols (e.g., `as->`, `cond->`, `condp->`, `some->` etc.) that are also missing on the list which I plan to add soon.
- `tests.keyword_char` and `tests.symbol` had redundant characters in them.
- `+` and `+'` were missing on the core symbols list as a regression introduced by commit 74fca7c .
Please note that there are some `FIXME`es in the tests. I'm planning to fix them soon once this …

[clojure mode] Add tests.

---

mode/clike/clike.js

A single quote in scala indicates the start of a symbol literal (like 'x), not a string, so should not be paired with a closing single quote.
See https://www.scala-lang.org/files/archive/spec/2.12/01-lexical-syntax.html#string-literals and https://www.scala-lang.org/files/archive/spec/2.12/01-lexical-syntax.html#symbol-literals for more information.

Do not autoclose single quotes in scala mode

---

mode/clojure/clojure.js
mode/clojure/test.js

This PR:
- reverts some of the previous code and uses `===` for equality checks.
- gets rid of the unreliable and sloppy regular expression-based heuristics for identifying forms that have body parameter and instead uses a purely whitelist-base approach.
- adds a few other forms that have body parameter to the indentation list.
- refactors the tests for forms that have body parameter.

[clojure mode] Refactoring.

---

mode/r/r.js

this is a very minor change, and it just looks better to have `function(x=TRUE)` to highlight this, similar to as it would be `x=NULL`. Also note that you can't assign anything to `TRUE` in R.

R: highlight TRUE/FALSE similar to NA, etc.

---

mode/scheme/scheme.js

Also fixes `#;` comments
Fixes https://github.com/codemirror/CodeMirror/issues/5574

Scheme mode fixes: properly marks 'atoms and '(lists of s-exp)

---

mode/mscgen/mscgen.js
mode/mscgen/mscgen_test.js
mode/mscgen/msgenny_test.js
mode/mscgen/xu_test.js

- The xù and msgenny mini-languages grew a new option keyword
- Xù grew some new attribute keywords (one a while ago, three very recently)
This PR adds these to the mscgen _mode_ in which xù and msgenny are defined.

[mscgen mode] Add new keywords for xù and msgenny

---

keymap/vim.js
test/vim_test.js

This will allow for more powerful mapping capabilities like arbitrary command
remapping, rebinding the home row, etc.
This doesn't quite match Vim's non-recursive behavior because there's no support
for non-recursive keyToKey mappings. Without this support, we'd just be creating
normal, recursive keyToKey mappings which I think would be even more frustrating
and/or surprising (e.g. two inverse non-recursive maps would cause infinite recursion).
Once this support is added for this, though, it will be trivial to create these mappings
at the end of the added function and achieve the most accurate behavior.
One potential paper cut with this implementation is that multiple calls to `unmap` may
be required to fully remove the `noremap`ed values. I think this isn't that severe though
because …

Add a non-recursive map command to the Vim API

---

mode/d/d.js

Comments are not working for d lang. I tried with following snippet
```
editor.execCommand('selectAll');
editor.toggleComment()
```
I checked and tested that for d lang mode 
`options.lineComment || mode.lineComment are undefined `

Fix comments for d lang mode

---

keymap/vim.js
test/vim_test.js

Repeating inserts with more than one character was broken because `vim.lastSelection.visualBlock` was converted to boolean after the introduction of multiple selection support.

[vim] fix insert mode repeat after visualBlock edits

---

src/input/input.js

Fixes #5613.
An alternative fix here would be to ensure that lastCopied’s text always includes a trailing newline when it’s line-wise.

Ignore lastCopied if not paste.

---

mode/clike/clike.js
mode/clike/test.js

From C++ Standard
Each name that contains a double underscore (__) or begins with an
underscore followed by an uppercase letter (2.11) is reserved to
the implementation for any use.
From C Standard
All identifiers that begin with an underscore and either an
uppercase letter or another underscore are always reserved for any use.
Turns these all into "builtin".

Add support for _[A-Z].* and __.* types to clike languages.

---

mode/clike/clike.js

Adds "inline restrict asm fortran" to C keywords (C99)
Fixes up missing spaces in x-nesc and x-objectivec that would've caused them to miss keywords
Adds all Objective C keywords for properties, nullability, Automatic Reference Counting and instancetypes.
Removes invalid Objc Atoms: NILL ON OFF and adds missing Nil and nil.
Note that _Bool _Complex _Imaginary that were removed from ObjC will "return" once https://github.com/codemirror/CodeMirror/pull/5624 is in (and will appear properly in C++ and C as well).

Expand keyword support for ObjC (and update C/C++ to include new keywords)

---

AUTHORS
bin/authors.sh

(and added myself)
The main change here is to make sure that Google Inc. gets changed over to Google LLC (our proper name now).

Change Google Inc. to Google LLC

---

mode/clike/clike.js
mode/clike/test.js

Updates the cTypes list to cover newer types (c11) and by
default picks up anything ending in '_t' as a type as defined
by the POSIX standard (and generally adopted by C compiler types
such as int16_t int32_t wchar_t etc).

[clike mode] Update default cTypes

---

mode/javascript/javascript.js
mode/javascript/test.js

Fixes #5660: adds support for this case:
```js
function a({ ['hello world']: helloWorld }) {
return helloWorld;
}
```

Permit quoted names for object destructuring in JavaScript syntax

---

addon/hint/show-hint.js

We're working on a new feature for [Playroom](https://github.com/seek-oss/playroom) where you can [detach the code editor from the main window](https://github.com/seek-oss/playroom/pull/7) and open it in a new window. This has highlighted an issue in the `show-hint` addon.
Currently, `show-hint` references the globals `window` and `document` to make layout calculations and add elements to the page. In our case, the code is executing in the parent window, so these global references are actually pointing at the wrong window. When writing code in the popup window, the suggestions are instead rendered to the parent window ([video link](https://cl.ly/92433d9175fd)).
To fix this, we ensure that references to `document` and `window` are scoped to the window that contains the textarea. We achieve …

Support cross-window hint rendering

---

mode/css/css.js
mode/css/test.js

In css `--` is a legal css custom property. CodeMirror gets confused when it is used though.
Fixes #5686

[css] support double dash css variable

---

addon/edit/matchbrackets.js
keymap/vim.js
test/vim_test.js

CodeMirror supports vim text objects [1] enclosed in parentheses, curly braces, square brackets, but **not** angled brackets. This is a known bug, and a previously documented TODO item in vim.js.
[1] http://vimdoc.sourceforge.net/htmldoc/motion.html#object-select

Allow vim-mode to select text enclosed in angled brackets.

---

mode/soy/soy.js
mode/soy/test.js

- changed classification of param-def-type to "type" instead of using "variable-3"
- updated tests to match this expectation
This will provide more accurate syntax highlighting and make the parameter types standout better for theming.

soy mode - classify param def type as type token

---

mode/soy/soy.js
mode/soy/test.js

This PR updates the {call /} command in soy mode to better support namespaced template names.
- updated "templ-ref" to match namespaced templates e.g.
my.namespaced.component.element. The existing regex matches the first
word and nothing after the "."
- updated "templ-ref" to treat all "." templates as variable-2.
Local templates are the only ones capable of starting with a dot and
because a template earlier in the file can reference a local template
later in the file, there are no guarantees of it being in the variable
list. Treating all .templates as local is more consistent and
predictable for syntax highlighting.
Here is a link to test out the regular expression I added: https://regexr.com/44okk.  It should work with local templates and namespaced templates.

soy updated "templ-ref" namespaces and local templates

---

addon/lint/yaml-lint.js

This still works transparently for single-document YAML.
https://yaml.org/spec/1.2/spec.html#id2800132

Allow linting of multi-document YAML stream

---

mode/soy/soy.js
mode/soy/test.js

Highlights { true } or { false } as atoms.  Also highlights all number literals.
- added tokenization for decimals
- added tokenization for hexadecimals
- added tokenization for true/false
- added test cases for those new atom tokens

[soy mode] boolean and number tokenization in expressions

---

mode/soy/soy.js
mode/soy/test.js

- modified the decimal expression to support scientific notation
- added tests to verify new highlighting behavior
I was looking through the expressions and realized I missed this one.  I think this might be the last atom change that soy needs for expressions.

[soy mode] add support for scientific notation

---

mode/css/css.js
mode/css/less_test.js
mode/css/scss_test.js
mode/css/test.js

- created a css function regexp with a positive lookahead for (. There
are still a few cases with IE functions that have . and : in it that
this does not catch.
- folded url/domain/regexp into that css function regexp including the
special string tokenization that was in place already
- updated css, less, and scss tests to reflect this new tokenization

[css mode] more consistent css function tokens

---

src/input/TextareaInput.js

The current solution consists in focusing the
input when the scroll container capture a paste
event, which does not work on Firefox.
In order to fix this, creating a new paste event,
copying the clipboardData and dispatching it
on the textarea seems to do the trick.
This works on Firefox 64, with the
config set to true.

Fix middle-click paste on Firefox.

---

mode/soy/soy.js

The {element} command is a new feature in Soy.

[soy mode] Add {element} as valid indenting tag.

---

theme/lesser-dark.css
theme/vibrant-ink.css

Lightening the blue link color (cm-link) on vibrant-ink and lesser-dark so that links show up better against the dark background.
theme/vibrant-ink.css     Before/After
theme/lesser-dark.css    Before/After

Update to dark themes

---

keymap/vim.js
test/vim_test.js

In Vim's command mode, forward-delete (Delete on PC or fn-delete on Mac) should
behave the same as 'x': delete the character under the cursor. Due to a bug in
CodeMirror's emulation, this wasn't happening before.
This change adds the proper support, along with tests for forward-delete.
Relevant issue: #5781

Add proper emulation for forward-delete in Vim.

---

CHANGELOG.md
doc/releases.html

Hi! 👋
Wondering why I didn't have a `/lib/codemirror.js`, I grepped through the repository, and found this instruction:
```
npm build
```
However, running it doesn't work:
```
$ npm build
npm WARN build `npm build` called with no arguments. Did you mean to `npm run-script build`?
```
I then guessed the correct instruction, `npm run build`. I suppose this is a typo, so I fixed the changelog and release notes accordingly.

Typo: `npm build` should be `npm run build`

---

addon/edit/matchbrackets.js

Here's a PR to fix `scanForBracket` support for user provided "brackets", e.g. `"`, that fails with type error.
Editor content with cursor position indicated by |:
```
"wo|o"
```
and calling 
```js
editor.scanForBracket(editor.getCursor(), 1, "string", { bracketRegex: /"/ })
```
results in type error: 
```js
matchbrackets.js:108 Uncaught TypeError: Cannot read property 'charAt' of undefined
at scanForBracket (matchbrackets.js:108)
at CodeMirror.scanForBracket (matchbrackets.js:216)
at <anonymous>:1:8
```
This fixes the issue at hand, making the call return the following, which is what you'd expect.
```json
{
"pos": {
"line": 0,
"ch": 4,
"sticky": null
},
"ch": "\""
}
```

Handle scanning for user provided brackets, e.g. "

---

theme/panda-syntax.css

https://codemirror.net/demo/theme.html#panda-syntax
https://adobe-fonts.github.io/source-sans-pro/ is a proportional font family by Adobe (the "Source" in the name refers to being open source).
https://adobe-fonts.github.io/source-code-pro/ is a matching monospace font family.
(screenshots in chrome on fedora)
cc @siamak

panda-syntax theme: use monospaced Source Code Pro instead of Source Sans Pro

---

mode/clike/clike.js

Currently, clike mode will assign token "type" to C++ variable decls like:
```cpp
int m_total_population;
```
because the regex `.+_t` matches the `_t` part of total. The rule should only apply to names that end in `_t`, as referenced by the link in the comment above the function.

Fix clike mode to only match "_t" at the end of an identifier

---

addon/hint/xml-hint.js
doc/manual.html

For example, typing "happy" to match completions "very-happy", "not-so-happy", "happy".
Useful for XML with longer, composite names.

[xml-hint addon] Optionally match in middle

---

addon/edit/continuelist.js

When creating an overlay mode from e.g. `gfm`, which has `markdown` as an `innerMode`, we need to recursively compute `innerMode` via `CodeMirror.innerMode` to correctly determine `markdown` descendant mode.
Fixes part of #5790.

Recursively compute innerMode in continuelist addon

---

src/edit/methods.js
src/edit/mouse_events.js

This change attempts to cancel any active selection prior to swapping the document in the `swapDoc` method in order to avoid conflicting information about the selection range. See the problem described in #5821.
Fixes #5821

Cancel selection before swapping document

---

addon/hint/xml-hint.js

If typing `attribute="` and by `closetag` it becomes `attribute=""` and user presses `Ctrl-Space` to autocomplete and the completion is `"x"` then by this fix  it nicely gives `attribute="x"` instead of obnoxious `attribute="x""`.
Intentionally coded to cause least change to previous behavior, to deal with the frequent most obnoxious case.
Resisted temptation to make changes affecting other cases too.

[xml-hint addon] Prevent extraneous quote

---

addon/edit/closetag.js

When user types `<atomic>` substitute `<atomic/>` if so configured.
In XML closing is required, and this option allows to automatically direct users towards entering
```
<very-long-but-empty-element attribute="something"/>
```
instead of
```
<very-long-but-empty-element attribute="something"></very-long-but-empty-element>
```
If necessary in an exceptional situation, however, user can easily override by removing the `/` in `/>` and type `</` to get a closing tag.

[closetag addon] Optionally prefer empty-element tags

---

addon/lint/html-lint.js

HTMLHint's v.0.11.0 added some structure changes to the HTMLHint Class. Because of that it is not being properly loaded within CodeMirror. This PR fixes that.
For better understanding on the problem, check the [differences on HTMHint's code](https://github.com/htmlhint/HTMLHint/commit/85a1c78984a8ec09ab17595efba2e6ac479e6f31#diff-7eb52b366866677666470e019283c8ea).

Adding compatibilty with HTMLHint 0.11.0

---

addon/search/matchesonscrollbar.js

The scrollbar annotations may fail to match search query under certain circumstances. This happens when the search cursor is `multiline: false`.
The matchesonscrollbar addon does not have a way to indicate `multiline: false`, the multiline status is heuristically determined and because of this it may end up being opposite of the status of the search cursor used by the search addon.
1. Go to online demo page for CodeMirror search feature: <https://codemirror.net/demo/search.html>.
1. Replace the CodeMirror editor content with the following text:
```! https://github.com/uBlockOrigin/uAssets/issues/2380
sportnews.to##+js(abort-on-property-write.js, KillAdBlock)
! https://github.com/uBlockOrigin/uAssets/issues/2382
0mniscient.github.io##+js(bab-defuser.js)
! …
```

[matchesonscrollbar addon] Fix possible discrepancy with search query

---

mode/swift/swift.js
mode/swift/test.js

Fixes #5793, a bug that was introduced in PR #5675. I'm working for and contributing this code on behalf of @CoderPad.
While writing this, I discovered a couple other bugs with Swift strings that I don't plan to work on at the moment (pre-existing bugs, not regressions; let me know if you want me to file a separate issue for these):
-The mode does not flag it as an error if you fail to include a newline after the opening `"""` or before the closing `"""` of a multiline string
-The mode doesn't properly highlight strings which use [extended string delimiters](https://docs.swift.org/swift-book/LanguageGuide/StringsAndCharacters.html#ID606)

Swift: properly handle empty strings

---

addon/hint/show-hint.js

See #5854.
I tested it on the `complete` demo but did not commit changes to the demo file since I believe that having a `container` is not the most common usage. Let met know if you would prefer that this demo uses a container.

[hint addon] Offset the hint to position it correctly when hintOptions.container is given

---

keymap/vim.js
test/vim_test.js

fixes:
- repeat for changes made with I in block selection mode being applied at the lastSel instead of current cursor
- missing text object for \` 
- desired column changing to infinity when moving down at the end of the file
- extra fatCursorMarks remaining in the document after using c from block selection mode

[vim] fix issues related to visualBlock mode

---

keymap/vim.js
test/vim_test.js

`vimGlobalState.macroModeState.latestRegister` was only ever updated when defining a macro. This change updates it when running a macro too so that `@@` actually repeats the last macro as it does in vim

[vim] fix @@ to rerun last run macro

---

keymap/vim.js
test/vim_test.js

This fixes underlying issue of https://github.com/codemirror/CodeMirror/pull/5547, which was happening because event handler is called after removing it, if it is removed in an operation.
Also refactors the test file to correctly handle function calls that are expected to fail.

[vim] Fix fat cursor remaining after the O command

---

keymap/emacs.js

Since "redo" is generally assigned to Ctrl+Y, we lose this binding
when using the Emacs keymap. The Emacs default for "redo" is a bit
complicated, but since we're using Ctrl-Z for "undo", it makes sense
to have Ctrl+Shift-Z for "redo".

[emacs] Add "redo" keybinding in Emacs keymap

---

addon/merge/merge.js

This was causing exceptions to be thrown when using custom markers.
Evidence:

[merge addon] Fix typo in hasMarker()

---

doc/manual.html
src/edit/options.js

It doesn't have a very useful meaning per https://en.wikipedia.org/wiki/Specials_(Unicode_block), but more notably it currently shows up as an invisible character and thus it's very easy to mess up documents with it.

Add U+FFFC as a default replaced special character

---

doc/manual.html
src/model/selection_updates.js
test/test.js

Per issue #5763. Hopefully it's this simple, seems to work for me. 
Would probably be good to add tests that the precedence works right when both options are provided. I'm having trouble running the tests locally though, `npm run test` produces errors like `ReferenceError: Can't find variable: addDoc (localhost:3000)`.

Add preventCursorLeft/preventCursorRight options for atomic markers

---

keymap/vim.js

It sometimes falls behind, highlighting for characters you typed in the past. This should drop the events it fails to handle in time.

[vim] throttle highlightSearchMatches

---

doc/realworld.html

Fixed link to GWT wrapper extension (was wrongly inserted into previous pull request)

Fixed link to GWT wrapper extension

---

mode/javascript/javascript.js
mode/javascript/test.js

Note that the new regular expression is more permissive than
the spec proposal, e.g. `0_._1` or `1__2` are not valid numbers.
However, filtering out these cases would make the tokenizer
unnecessarily complex.
Fixes: https://github.com/codemirror/CodeMirror/issues/5926

[javascript mode] Support numeric separators

---

keymap/vim.js
test/vim_test.js

currently in vim mode 
replacements behavior does not match vim's
for substitutions like :%s/\//slash/g supposed to replace "/" -> "slash"
however currently in codemirror it shows notification "no matches for \\"
the provided PR fixes the behavior in vim pcre mode to match vim's

[vim mode] match vim char escape substitution behavior

---

keymap/vim.js
test/vim_test.js

for #5753
in vim mode substitutes & with the match, to match the vim behavior

[vim mode] #5753 Feature request: Support &/$0 in vim substitute

---

addon/search/search.js

When `\` is followed by any other character, it will not be
interpreted as an escape sequence, i.e. `\3` will be
interpreted as literal `\3`, not as `3`.
Fixes https://github.com/codemirror/CodeMirror/issues/5428

[search addon] Escape sequence only for \n, \r, \t and \\

---

mode/sparql/sparql.js

This regex is ES3-compliant but it misses non-BMP characters specified in SPARQL standard.
This should be preferred if compatibility with old JavaScript is wanted. Else the other PR #5937 should be preferred. Both PR are excluding.
Closes #5935

[sparql mode] Non-ASCII variable names

---

mode/javascript/javascript.js

cf. #2993 and 27fe44c which fixed the analogous issue for single-quotes, double-quotes and regex literals.

[javascript mode] don't detect backtick-enclosed fatarrows

---

mode/javascript/javascript.js
mode/javascript/test.js

The regexp for parsing numbers with numeric separators is too
broad. This way, we mistake properties starting with underscore
to be numbers.

[javascript mode] fix tokenizing of underscore properties

---

mode/dart/dart.js

This adds additional hooks to the Dart mode. This uses the `variable-2` token type for tokens matching `Uppercase` or `_UppercaseWithUnderscore` where `_lowercaseUnderscore` are assumed to be normal variables.
The Dart mode uses the `clike` mode, so this uses the `hooks` feature from that to avoid writing a  custom `token()` function.

Dart class tokens

---

doc/realworld.html

The domain http://codev.it is Inaccessible,  the [latest twitter](https://twitter.com/codevit) was post on Sep 2015.
It's better to remove it.

remove unmaintained codev.it

---

addon/fold/foldgutter.js

Currently if I want to specify a custom widget for folded ranges it would not work when I fold a range using the gutter. This happens because `onGutterClick` function passes through only `rangeFinder`  option.
The solution is to pass all options, which is supported by the `foldCode` method.

Foldgutter: make it possible to redefine the `widget` prop

---

mode/handlebars/handlebars.js
mode/handlebars/index.html

This PR adds support for triple mustaches like 
```hbs
{{{rawHtml}}}
```
that can be used in Handlebars to avoid HTML-escaping the output.

[handlebars mode] add support for triple mustache tags

---

mode/asterisk/asterisk.js

Originally added to the AstLinux Project:
https://github.com/astlinux-project/astlinux/commit/fa426d86f589a8557ce566deb18d13b4046c8488
Tested to work as expected.

[asterisk mode] Add block-comment support

---

lib/codemirror.css
src/measurement/position_measurement.js

Currently, `lib/codemirror.css` contains a broad selector for `.CodeMirror pre` in a couple places. It seems intended to match the `pre` tags corresponding to `.CodeMirror-line` and also the ones for measurement.
However, if you want to create a widget or line widget that contains a `pre` tag, it ends up inheriting a bunch of styles you don't expect.
Since `pre` tags seem to only be created in a few places, I searched through the code and made sure they always have an appropriate classname. Then I modified the selector to only target the desired CodeMirror elements.

Make ".CodeMirror pre" selector more specific

---

addon/fold/foldgutter.js

UI begins to lag when a block of text over 10000 lines are folded. Browser will freeze for minutes when line count increased to 100K.
The isFolded function only requires looking forward, optimised the code by passing the -1 argument to the TextMarker.find method.
Code folding is now instantaneous even with 100K lines involved.

significant speed optimisation when large amount of lines are folded

---

addon/display/placeholder.js
lib/codemirror.css
src/measurement/position_measurement.js

Turns out my previous PR #5963 did actually break something -- the `placeholder.js` addon was rendering wrong without these styles. This PR re-adds them for the `pre.CodeMirror-placeholder` class.
The placeholder appears to be the only addon that does this.

Fix placeholder styling after <pre> change

---

src/edit/fromTextArea.js

When CodeMirror is initialised with `{leaveSubmitMethodAlone: true}`, `realSubmit` is never filled with the original submit handler, leaving it null/void. 
When `finishInit` runs, it then **overwrites** the `submit` method with a null/void value. As a result, the application I'm working with breaks when it tries to save the form CodeMirror is in. 
[As an aside, I had to use `leaveSubmitMethodAlone` in the first place because I ran into some submit issues in another scenario (with moved/removed codemirror instances IIRC). I can't reproduce that now; it might have been an older version.]

Prevent removing textarea.form.submit handler with opts.leaveSubmitMethodAlone

---

mode/clike/clike.js

Fix `indent` for lambda expression with parameters, [for  example](https://kotlinlang.org/docs/reference/coroutines/cancellation-and-timeouts.html) – in line  `println("job: I'm sleeping $i ...")`:
After indent code like:
```kotlin
repeat(1000) { i ->
println("job: I'm sleeping $i ...")
delay(500L)
}
```

Fix Kotlin indent for first line in lambda with params

---

addon/fold/foldgutter.js
addon/scroll/annotatescrollbar.js

The setTimeout/clearTimeout overhead of re-scheduling on every change in a large operation can be significant. This cuts the time of a particularly large operation I was testing from 5s to 2.5s (replacing some text in ~5000 lines). The majority of the rest of the time coming from rescheduling of the highlight worker inside the startWorker call.

Schedule a redraw on changes instead of change

---

mode/meta.js

Add common extensions (wl and wls) for Wolfram Language, which is the same as Mathematica syntax.
https://reference.wolfram.com/language/ref/program/wolfram.html

add wl and wls file extensions

---

doc/realworld.html

Tistory is blog service in South Korea.
Tistory uses CodeMirror at post markdown/html editor and skin editor.

[real world] add Tistory

---

addon/fold/foldgutter.js

On large documents foldgutter spends a lot of time (0.2s, 0.5s, or even a second) unnecessarily forcing CodeMirror to recreate the unchanged mark elements:
With this PR on a large document we'll spend 10+ times less on folding+rendering:
* The built-in indicator element for open/folded states differs only by its className so we can optimize for this case. This PR leaves the old marker unchanged if its className contains the new class.
* With a user-provided element the only case we can optimize for is to skip removing the marker when there were none. Such a check is implemented in this PR.
* `classTest` function was copied from [/src/util/dom.js](https://github.com/codemirror/CodeMirror/blob/master/src/util/dom.js) because AFAICT we can't use …

[foldgutter] reuse old markers if indicatorOpen/Folded is string

---

mode/pug/pug.js

Fixes #6021.
Correct number of arguments in function calls to match function definitions.
E.g.
https://github.com/codemirror/CodeMirror/blob/268de539a8be79b59a518cfc0c00c22ad98739f6/mode/pug/pug.js#L143
https://github.com/codemirror/CodeMirror/blob/268de539a8be79b59a518cfc0c00c22ad98739f6/mode/pug/pug.js#L548
Becomes
`      || yieldStatement(stream)`

Fix number of arguments in function calls

---

mode/yaml-frontmatter/yaml-frontmatter.js

This allows to end yaml-frontmatters with either `---` or `...`, as
suggested [on the discussion board][1]. The old behaviour was to just
accept `---`.
[1]: https://discuss.codemirror.net/t/pandoc-markdown-style-yaml-frontmatter/2182

[yaml-frontmatter mode] Allow pandoc-style closing with `...`

---

addon/comment/continuecomment.js

When pressing <kbd>Enter</kbd>:
* line comment will always be continued if the next line is a line comment
* line comment won't be continued if cursor is at EOL or inside trailing space(s) at EOL
* line comment won't be continued if cursor is at position 0 and the line comment starts at 0 too. An empty line will be added above just like before but the original line won't change, whereas previously it would be mangled like `// // comment`.
* block comment won't be continued if it's inside a line comment e.g. `// /*`
* the indentation of block continuation respects `indentWithTabs` option.

[continuecomment] skip some edge cases, respect indentWithTabs

---

mode/clike/clike.js

Objective-C++ is a superset of Objective-C and C++, so adding syntax support for it just requires combining both rulesets. I separated out some of the larger string constants to avoid some of the most egregious duplication (keywords, builtins, etc.)

Add Objective-C++ Support

---

mode/dart/dart.js

This adds support for Dart 2.6 extension method syntax

Add "extension" and "on" keywords to Dart syntax

---

mode/meta.js

Fixes a bug where findModeByExtension does not return a result for me. This is when the filename for which I want to derive the mode is uppercase. For some programming languages like R it is common to write the filename extension in uppercase. The extensions in the info structure of CodeMirror are however stored in lowercase, i.e. in this case there wasn't a match... 
Since findModeByName and findModeByMIME are both case insensitive, I suggest to make findModeByExtension  (and thus findModeByFileName) also behave that way, so that it is consistent.

makes findModeByExtension case insensitive

---

mode/elm/elm.js

Hello! 
We noticed some issues with a product I maintain with multiline string formatting in Elm modules, see issue here: https://github.com/ellie-app/ellie/issues/91.
This copies over changes made to the Elm mode found in https://github.com/elm/elm-lang.org/blob/master/editor/cm/mode/elm.js
This an admittedly _lazy_ solution but this was originally modified by the creator of Elm and it seems to be working.

Update Elm mode

---

mode/sql/sql.js

Fix syntax highlight for pgsql mode as PostgreSQL does not require backslash to be escaped.
Add support for escape constant as mentioned with ref to:
https://www.postgresql.org/docs/current/sql-syntax-lexical.html#SQL-SYNTAX-STRINGS-ESCAPE
Below are the sample queries to test:
SELECT 'select c:\data\out\'||oid||'.csv' from pg_class;
select E'\'', '123\';
Attached are the screenshots of working example where the above queries works fine - pgAdmin4.

Fix syntax highlight for pgsql mode for backslash and escape constant

---

mode/soy/soy.js
mode/soy/test.js

Fix indentation after a {literal}{/literal} block.

[soy] Fix indentation after a {literal}{/literal} block.

---

src/display/update_line.js

Removal of line widgets is broken in 5.50.0 due to invalid classname check.

Fix: Broken line widget removal

---

mode/julia/julia.js

Fix for issue [#6071](https://github.com/codemirror/CodeMirror/issues/6071), Julia mode has a indent problem.
This patch fixes the problem by closing all scopes which has been opened inside an array or generator when the closing char is found.

[Julia mode] Restore indentation when closing an array or generator.

---

src/edit/drop_events.js

Fix for issue [#6098](https://github.com/codemirror/CodeMirror/issues/6098). When multiple files are dropped into the editor and any of these are invalid, then none of the files content is pasted.
With this patch all valid files will be pasted and all invalid rejected.

If valid and invalid files are drag n dropped, paste all valid files

---

mode/rust/index.html

changed invalid type names (e.x. `int` to `i32`, `some` to `Some`)

Fixed type names of Rust demo code

---

doc/manual.html

The external link to the ternjs.net demo page returns a 404 error; this PR corrects it.

Fix broken link in manual

---

keymap/vim.js
test/driver.js
test/vim_test.js

- implements `gi` `gI` `gJ`
- fixes behavior of the `R` key in visual mode
- fixes behavior of <code>``</code> and <code>`'</code> which are supposed to go to the last jumplist position instead of last place where cursor was moved (the changed behavior matches the description in https://vim.fandom.com/wiki/Using_marks, and results of manual test using vim 8.2)

[vim] implement gi gI gJ

---

addon/lint/lint.js

Currently it's impossible to style lint tooltips in a theme CSS file because tooltip elements are inserted directly into `body` element.
This PR changes `lint.js` addon so that lint elements have theme class name added.

Add theme class name to lint tooltips

---

test/driver.js

Remove hard coded filter which only allowed vim tests to run.
Also improved the unique naming algorithm's time complexity from O(n^3) to O(n). With these 2000 tests this will reduce the iterations needed from 2 000 000 to 2000 iterations (or if all tests had the same name 4 * 10^9 iterations).

Fix test driver

---

mode/soy/soy.js
mode/soy/test.js

Add support for map, list and records.
Example of code which is now supported:
{@param name: [test: number]}
{@param numbers: list<number>}
{@param strToNumMap: map<string, number>}
{let $list: [['a'], ['b']] /}
{let $list2: [$a + 1 for $a in $name if $a >= 3] /}
{let $record: record(test: 'a', foo: 'bar') /}
{let $map: map('test': 'a', 4: 'bar') /}

[Soy] Improve map, list, record and list comprehension highlighting

---

addon/tern/tern.js

The current implementation of tern.js is appending the tooltip to the body.
When applied the codemirror context inside a shadow root, tooltips are falling out of the root component.
This change would append the tooltip to the container of codemirror hint options if it has else it will default to document.body

[tern addon] Allow appending the tooltip to the codemirror hint options container if exists

---

addon/edit/continuelist.js

In CodeMirror, using markdown mode and the continueList addon, blockquotes are not getting reset when the last line contains `> `
Currently:
```
> I am a blockquote
> 
I am still marked as a blockquote and get markdown style
```
This fix:
```
> I am a blockquote
> 
^ this will get replaced like other lists, and I am no longer marked as a blockquote
```

Fixes blockquote continuing without `>` in continueList

---

mode/stex/stex.js

TeX user is free to declare macros with any name and in case of names such as `constructor` or `hasOwnProperty` etc., mode was picking prototype properties instead of default plugin.

sTeX: Ensured that tag does not clash with object prototype props

---

mode/protobuf/protobuf.js

Add folding for Protobuf's TextFormat. The syntax uses `{}` mainly. But also has `[]` (rare) and `<>` (legacy?). I don't believe `brace-fold` supports `<>` but I've never seen it in the wild so it's probably not too useful to support.
See [text_format.cc](https://github.com/protocolbuffers/protobuf/blob/master/src/google/protobuf/text_format.cc) for the closest thing to a grammer.

Brace folding for Protobuf mode

---

mode/markdown/markdown.js
mode/markdown/test.js

Reasons expressed by Michael in #6129 seem good enough, and a dash can be used for multiple purposes. I believe many people start writing lists right after an introductory sentence, and may be puzzled at why the previous line suddently becomes a header for a second.

Markdown: Disallow single dash for a setext header, fixes #6129

---

mode/powershell/index.html
mode/powershell/powershell.js
mode/powershell/test.js

Today backslashes are highlighted with the `cm-error` class in Powershell code:
This PR treats a backslash as punctuation, removing the error highlight:

Fix issue with backslashes being highlighted as errors in Powershell code

---

addon/dialog/dialog.js

The input field of a dialog loses focus when switching to another tab or dev tools. This fix checks to see if the new focus target is inside the window (i.e. not null) before closing the dialog.
I have also changed the target to be the dialog div, instead of the input field. This better suits sites that add other elements inside the dialog.
Tested and working in Firefox, Chrome, Safari and IE > 8.
IE 8 retains previous behaviour, since `relatedTarget` is undefined.

Fixes #4804 dialog closes when tab loses focus

---

keymap/vim.js
test/vim_test.js

Vim's visual mode allows the cursor to be positioned over EOL.
This change fixes a bug where that EOL behavior only worked when
in visual block mode.

[vim keymap] Fix EOL handling in visual mode.

---

keymap/vim.js

This fixes a bug where a mouse click to the right of a line
results in the cursor apparently over EOL, even though it is actually
positioned over line.length-1. Cursor position should display over
EOL only in visual or insert modes. Insert mode is handled by default
cursor behavior and visual mode is handled by the fake cursor, so
we should remove the special cursor EOL handling here and just clip
to show the cursor in the right place.

[vim keymap] Don't mark fat cursor over EOL.

---

addon/runmode/runmode-standalone.js

This PR updates the `runMode` function in runmode-standalone.js with 3 commits from [runmode.js](https://github.com/codemirror/CodeMirror/blob/master/addon/runmode/runmode.js):
- https://github.com/codemirror/CodeMirror/commit/7e35f03ad1639d92735c8dee1e1b5c86a727c873
- https://github.com/codemirror/CodeMirror/commit/53bc4b1f54670c827662d5210a37b35e63a07c39
- https://github.com/codemirror/CodeMirror/commit/64113ec97bb73c2a740d42d56021acb01ce05a92
The first commit from runmode.js allows the `callback` in runMode to be a function, as mentioned in https://codemirror.net/demo/runmode.html and https://discuss.codemirror.net/t/runmode-standalone-callback/2357. The last two commits fixes a copy-and-paste bug from IE.

Update runMode with changes from runmode.js

---

addon/hint/show-hint.js

The `scrollToActive` function used to have a `3px` offset hardcoded, which matches the default style (`padding: 2px; border-width: 1px;`). Custom values for these these style attributes would lead to a small visual bug:
For example, with custom `padding: 0px`
Behaviour with default style is unaffected.

[hint] Nicer scrolling with non-standard padding

---

doc/manual.html

This addresses most of: https://github.com/codemirror/CodeMirror/issues/6206
The two functions I didn't end up adding are:
1. `InsertModeKey`- as it doesn't seem to do anything.
2. `_mapCommand(command)` - this seems to be a private method and it is probably easier to use `mapCommand`. Plus I'm not entirely sure how to properly describe what makes a valid `command`
A few points I was confused by:
1. How to describe the `origin` argument to `findKey`. I'm not sure what valid values are for this or even what it describes so I haven't added any description of it.
2. Whether to write `ctx` as `context`? In the existing documentation it is written as `context` (e.g. for map), however in the actual function definition it is written as `ctx`. So I erred towards accurately reflecting the source …

Add functions to vimAPI documentation

---

addon/search/searchcursor.js
mode/python/python.js

There is a small typo in addon/search/searchcursor.js, mode/python/python.js.
Should read `compatibility` rather than `compatiblity`.

docs: Fix simple typo, compatiblity -> compatibility

---

addon/hint/show-hint.js

**Fixes a minor visual bug:**
The picked hint might push the cursor out of the screen - this scrolls the cursor back into view. (Would normally happen after the next keypress.)

[show-hint] Scroll cursor into view after picking.

---

demo/simplemode.html

Related issue: https://github.com/codemirror/CodeMirror/issues/6233
add "Currently negative lookbehind assertion for regex is not supported, regardless of browser support." in description of the "regex" property of the rule. This is documentation update and no actual code is modified.

Documentation update for simple mode: clarify that negative lookbehind assertion for regex is not supported

---

addon/runmode/runmode-standalone.js
test/lint.js

We use the standalone mode in DevTools in a worker, where `window`
does not exist. Instead, we can use `globalThis` which should be
the corresponding global scope in all scenarios. For older browsers
that do not support `globalThis`, we fallback to `window`.
Relevant DevTools change:
https://chromium-review.googlesource.com/c/devtools/devtools-frontend/+/2174418/1/front_end/third_party/codemirror/package/addon/runmode/runmode-standalone.js

Add support for globalThis in standalone mode

---

mode/dart/dart.js

Addresses most of #6268 
Types with `?` suffixed remain unsupported. I wasn't sure the best way to add this. Just duplicate (approximately) the list and add `?`?

Add `late` and `required` keywords, and `Null` and `Never` types to Dart

---

mode/meta.js

There is an unwanted space in the TiddlyWiki mode name. This PR removes it.

Remove unwanted space in TiddlyWiki mode name

---

keymap/vim.js
test/vim_test.js

I'm attempting to implement the `:!` command, but currently the name `!` isn't fully supported (adding an argument causes the command to not be found). This PR fixes it (for commands listed in [index.txt#ex-cmd-index](https://vimhelp.org/index.txt.html#ex-cmd-index)).
I was going to put `/^(\w+|!!?|@@?|[#&*<=>~])/`, but `!!` and `@@` don't take parameters.

[vim] Allow Ex-Commands with non-word names

---

mode/soy/soy.js

Instead of looking for explicit map or list change to look for the '<' to check for param type parameters.
Example:
`map<string, string>`
`list<string>`
Also removed unused `var peekChar = stream.peek();`

Fix bug with "map" in type name.

---

mode/markdown/markdown.js

This PR changes the default value for the option `fencedCodeBlockDefaultMode` in [markdown mode](https://codemirror.net/mode/markdown/) from `''` to `'text/plain'`. 
- Alternatively, the string value `'null'` works as well since [in meta.js, 'null' is the mode for plain text](https://github.com/codemirror/CodeMirror/blob/840464b337695d3c4fd2807bdd69e462e2f7d118/mode/meta.js#L107).
- An issue with using `''` as the default value is with how [`CodeMirror.getMode` is currently defined in `runmode-standalone.js`](https://github.com/codemirror/CodeMirror/blob/840464b337695d3c4fd2807bdd69e462e2f7d118/addon/runmode/runmode-standalone.js#L94): since `''` is not a valid mime or mode, an error is thrown.
- `text/plain` is a valid mime and `'null'` is a valid mode, and are both defined in the …

change fencedCodeBlockDefaultMode to 'text/plain' instead of ''

---

mode/soy/soy.js
mode/soy/test.js

Add support for index in for loops.
```
{template .bar}
{let $foo: [$a + $i for $a, $i in [1,2,3]] /}
{for $a, $i in [1,2,3]}
// ...
{/for}
{/template}
```
Fixed variable scope issue with list comprehensions. Variables defined inside a list comprehension could be accessed outside the list.

Add support for index in for loops and fix issue with variable scope issue

---

keymap/vim.js
test/index.html
test/vim_test.js

User can use `t` to operate on tag text objects. For example, given the
following html:
```
<div>
<span>hello world!</span>
</div>
```
If the user's cursor (denoted by █) is inside "hello world!":
```
<div>
<span>hello█world!</span>
</div>
```
And they enter `dit` (delete inner tag), then the text inside the
enclosing tag is deleted -- the following is the expected result:
```
<div>
<span></span>
</div>
```
If they enter `dat` (delete around tag), then the surrounding tags are
deleted as well:
```
<div>
</div>
```
This logic depends on the following:
- mode/xml/xml.js
- addon/fold/xml-fold.js
- editor is in htmlmixedmode / xml mode
Caveats
This is _NOT_ a 100% accurate implementation of vim tag text objects.
For example, the following cases noop / are inconsistent with vim
behavior:
- …

Support tag text objects in xml / htmlmixed mode.

---

doc/realworld.html

[Violentmonkey](https://violentmonkey.github.io/) is a userscript manager for many browsers. Its built-in userscript editor uses CodeMirror.

[real-world uses] Add Violentmonkey

---

mode/css/css.js

I just added a few missing ones from what I encountered:
1. property `all`
2. media feature `prefers-color-scheme`, with values `dark`, `light`

[css] add reserved words 

---

addon/scroll/annotatescrollbar.js
test/annotatescrollbar.js
test/index.html

PR for issue #6385 
The changes to annotatescrollbar.js will check to see if the current match is collapsed ("folded"). And if so, then use the first line of the markText.lines as the current line for the annotation. This addresses the 2 issues:
- If there is a match on the folded line and there are also matches within the folded content then when the fold is collapsed, we expect at least the match on the folded line to be annotated on scrollbar. But it's not.
- Matches hidden within a collapsed fold are not annotated on the scrollbar.
**Disclaimer:**
I'm not familiar enough with the wide scope of this project so I cannot guarantee that this will not have unintended side effects. That being said, I did my best to ensure that all lint/test cases are passing.

Annotate scrollbar when matches are folded

---

addon/hint/xml-hint.js

The diff before commit looked even smaller when ignoring whitespace with `git diff --ignore-all-space`.
This change optionally extends a chain of promises from a developer's attribute values function through `xml-hint.js` to `show-hint.js` function `fetchHints`, where it already is supported since at least commit 87d10fa in 2016.
Keeps working with arrays returned (without promises) just as it used to.
If promise fulfilling function throws and consequentially promise value is undefined then returns empty list.
First use case was a need for an online lookup of values, depending on context, on another attribute value, that could not be done ahead of time and should be done asynchronously.

[xml-hint addon] Allow attribute values function to return a Promise

---

keymap/vim.js
test/vim_test.js

Fixes #6223
Caveats: In theory you could record a macro into the register and fill it with text that way, or by programmatic means. Then it will show up in `:registers` and allow pasting via `"_p`.
([Line 2363](https://github.com/codemirror/CodeMirror/blob/6fcc49d5321261b525e50f111f3b28a602f01f71/keymap/vim.js#L2361) is where recording can be avoided, but that line is long enough already).
Edit: Or just leave '_' out of validRegisters. Works for change/delete, but not paste. (Pasting from nowhere is about as unusual as recording to nowhere).

[vim] Add black hole register

---

demo/vim.html
keymap/vim.js
test/vim_test.js

If we are given the following snippet of text:
```
A green green sky.
_
```
We can search for the word "green" with `/green`, and then use `gn` to
select the next occurrence of "green" in visual mode.
```
A green green sky.
-----
```
Alternatively, we can use `cgn` and then enter the word "blue" to change the
word "green" to "blue".
```
A blue green sky.
```
Then we can use the `.` operator to repeat the change:
```
A blue blue sky.
```
Addresses #3851.

Add vim emulation support for `gn` and `gN`.

---

addon/lint/lint.css
addon/lint/lint.js

This changes `lint.css` to be less reliant on the predefined severities (`error` and `warning`), in turn making it easier to define custom ones. Now all that needs to be done in order to define a new severity, e.g. `note`, is to add the following CSS:
```css
/* underline */
.CodeMirror-lint-mark-note {
background-image: ...;
}
/* icon */
.CodeMirror-lint-marker-note, .CodeMirror-lint-message-note {
background-image: ...;
}
```
Previously, it was necessary to copy many styles that were only available under the `CodeMirror-lint-*-error` and `CodeMirror-lint-*-warning` classes.

[lint addon] Use separate CSS classes for common lint styles

---

addon/hint/sql-hint.js

sqlhint.js: findTableByAlias() was receiving keywords with backticks still in place if used in the query - a helper function eachWord() only stripped commas and semicolons from the keywords, now stripping backticks as well.

Fixes #6331. Backticks are stripped from SQL query words before comparison

---

mode/css/css.js
mode/css/index.html

Fixes #6402. The new option is true by default (so no change for existing setups) and is scoped to the CSS mode only.

Adds option to turn off highlighting of non-standard CSS properties

---

mode/sparql/sparql.js

Do not treat the opening "<" character of an unprefixed Datatype IRI as an operator along with the preceding "^^" characters. e.g. the following literal contains three characters in a row, ^^< that are "operator characters" but the third is the first character of the atom that follows two operators.
"42"^^<http://www.w3.org/2001/XMLSchema#integer>
Respect the SPARQL 1.1 percent-encoding and backslash-escaping within the suffix of a prefixed IRI (and add colons to the set of allowable IRI characters). For example these are legal IRI atoms and with this change are highlighted as such..
foo:b\/r#xyz
foo:b%25r#xyz
To address a single issue of everything after the last "#" within an IRI (a common character in IRIs) being highlighted as if it were a comment in some common prefixed and …

Improve parsing of IRI atoms (sparql mode)

---

mode/meta.js

closes #6450 
The WebAssembly `wast` mode already exists, but it is not currently available via `meta.js`. This will apply to the `.wat` and `.wast` extension for now, but it looks like `.wat` and `.wast` [have separate meanings going forward](https://developer.mozilla.org/en-US/docs/WebAssembly/Text_format_to_wasm).

Add WebAssembly (wast) to meta.js

---

mode/stylus/stylus.js

Stylus language [supports block comments](https://stylus-lang.com/docs/comments.html) so this PR adds the missing props copied from the built-in css.js. Now we can use addons/comment.js and <kbd>Ctrl</kbd><kbd>Shift</kbd><kbd>/</kbd> hotkey to make block comments!

[stylus mode] allow block comments

---

mode/htmlmixed/htmlmixed.js
mode/soy/soy.js
mode/soy/test.js
mode/xml/xml.js

Add support for Soy Element Composition. It has the syntax in the form of
<{foo()}></>
This adds support to pass through allowEmptyTag and to support this mode in closetag.

Add support for Soy Element Composition.

---

doc/manual.html

I recently dug into the `show-hint`-add on, and noticed an odd behaviour: The `close`-event was not fired on the completion object when certain characters were pressed. Upon reviewing the source, I found several undocumented options and one undocumented event in the show-hint add-on.
As I am sure some people are already using the `endCompletion`-event which is being fired on the editor instance, I decided not to touch the source, and instead amend the documentation.
- Fix a few typos and grammar in the `show-hint` description
- Document the `closeCharacters` option for the `show-hint` add-on
- Document the `completeOnSingleClick` option for the add-on
- Document the `container` option for the add-on
- Document the `endCompletion` event, which is being fired on the cm-instance on …

Document all options for show-hint addon.

---

lib/codemirror.css

background-color: white; remains white on dark themes which doesn't suit dark background pages. Changing it to transparent to match the theme.

Fix white CodeMirror-scrollbar-filler on dark themes

---

mode/shell/shell.js

(a space is not required and the DELIMITER may be quoted for special meaning)
```
cat <<EOF
EOF
cat <<'EOF'
EOF
cat <<"EOF"
EOF
cat << 'EOF'
EOF
cat << "EOF"
EOF
```
Initial Issue #6468

Fix shell Heredoc for these cases:

---

addon/hint/show-hint.js

When working with the `show-hint` addon (very valuable in general, thanks!), I've come across situations when I had to customize its behavior.
I didn't want to highly customize the internal logic so I was able to simply add options modifying some of the taken actions.
However, I've made also two improvements not being behind the options:
- computing `startScroll` in `setTimeout` so it doesn't cause the forced reflow on init
- added a condition over the `this.scrollToActive()` call as it doesn't need to be scrolled to the first hint on init (especially that `selectedHint` is `0` by default) and it causes the reflow as well
I'd divide the options into two groups: functional and styling ones (having a performance impact).
Functional:
- `closeOnCursorActivity` - disable closing the …

Adding options customizing a behavior of `show-hint` addon

---

mode/index.html

Looks like there is only one missing.
bash$ `(cd mode; for f in */; do grep -Fq href=\"$f index.html || echo $f; done)`

Add missing languages link

---

addon/edit/matchbrackets.js

In `cm.off`,`Array.indexOf` on `_handlers` returns `-1` for a function defined within the scope of another function.
That leads to a memory leak.

[matchbrackets addon] Fix memory leak

---

theme/solarized.css

There were two small typos in the solarized palette...
`ligh -> light`

fix typos in solarized palette

---

mode/verilog/test.js
mode/verilog/verilog.js

This resolves #6227 support request, adding in missing construct support.
Additional tests created for these new scenarios, and all previous tests pass unedited.
Sorry, this is my first pull request...let me know if I need to tweak how I'm doing this. Thanks!

Update Verilog mode support

---

addon/wrap/hardwrap.js

This breaks an infinite loop triggered by wrapping a text containing a word longer than the targed width (e.g., a long URL).

Break an inifite loop in text wrapping.

---

CHANGELOG.md

Simply add the .html extension to the link.

Fix the search addon page link

---

doc/realworld.html

Previous url (clone-it.github.io) returns 404 because I changed github account.

[real world uses] Update "Clone-It" url

---

addon/hint/show-hint.js

I had to slightly change the behavior of `closeOnCursorActivity` flag. In fact, it became `updateOnCursorActivity`.
The reason is that it has been sometimes possible (quite often on Safari) to be stuck with multiple dropdowns.
I'm controlling the opening/closing of the hints from outside but `Completion#cursorActivity` is async as it uses `setTimeout`. As a result, it has been possible to have `new Widget` called twice without closing between so two dropdowns have been displayed (without any way to dismiss the previous one).
Then, I'd prefer to opt-out from the whole "update on cursor activity" functionality (not only closing) as I'm controlling that on my own from outside of the addon.
Thanks for checking this PR out :)

Extended the `closeOnCursorActivity` flag to be `updateOnCursorActivity`

---

addon/edit/matchbrackets.js
doc/manual.html

It's not uncommon to have non-matching brackets in MediaWiki wikitext source code. This is not always an error. Another reason why we want to disable this feature is that it's rather distracting while typing. We [temporarily patched our copy of the addon](https://gerrit.wikimedia.org/r/656119), but think it's worth having a proper config flag.
[Bug: T269096](https://phabricator.wikimedia.org/T269096)

Add highlightNonMatching config to matchbracket addon

---

mode/dtd/dtd.js
mode/ebnf/ebnf.js
mode/julia/julia.js
mode/markdown/markdown.js
mode/mscgen/mscgen.js
mode/oz/oz.js
mode/pegjs/pegjs.js
mode/pug/pug.js
mode/rpm/rpm.js
mode/sass/sass.js
mode/soy/soy.js
mode/sql/sql.js
mode/stylus/stylus.js
mode/tiddlywiki/tiddlywiki.js
mode/yaml-frontmatter/yaml-frontmatter.js
mode/yaml/yaml.js

Warning: This works only when the match() call is a StringStream.match(), not if it is a native String.match(). Please carefully review this and make sure this doesn't break anything.

Replace regex with faster string matches

---

keymap/vim.js
mode/clike/clike.js
mode/css/css.js
mode/cypher/cypher.js
mode/mscgen/mscgen.js
mode/php/php.js
mode/puppet/puppet.js

The method fails anyway (i.e. it acts as if there was no match) when the match is not at the start of the string. Adding the anchor does not change any behavior, but increases performance.

Add missing ^ anchors to StringStream.match() patterns

---

doc/realworld.html

Rename writeLaTeX to Overleaf in the list of real-world uses.
https://www.overleaf.com/blog/190-writelatex-is-continued-overleaf

Rename writeLaTeX to Overleaf

---

keymap/vim.js
test/vim_test.js

Fixes vim registers command when html tags present.
Fixes vim prompts in Firefox Developer Tools.
Sorry for the gnarly diff, but it had to be done.
I've also inlined the dialog function and searchPromptDesc constant var, which had exactly one reference each.
Background:
Firefox - the cmdline and search prompt has been broken in Firefox for a while, the `<input>` tag gets stripped out (when assigning to innerHTML in the dialog addon). Luckily constructing DOM nodes instead works.
`:registers` - This command prints out text you last copied/changed/deleted along with named/numbers registers. If you have html in your registers, the output is incorrect / interpreted.

[vim] fix html in dialogs/prompts

---

keymap/emacs.js
test/emacs_test.js

Related to #6581. Firefox Developer Tools flattens input elements when using innerHTML.
The existing test didn't have any assertions. No problem, it does now.

[emacs] goto line in firefox devtools

---

keymap/vim.js
test/vim_test.js

Fixes #6521 (and #5450).
The main issue was any change to line numbers wasn't taken into account. It's the bulk of this PR.
The other issue was the `index` variable being incremented (L5075) after the recursion (L5072). The test (L4073) was incorrect too.
*Note: a large enough number of matched lines will still cause a stack overflow error (as does recursive mappings and macros).*

[vim] Fix :substitute and :global commands when splitting or joining lines

---

keymap/vim.js
test/vim_test.js

Fixes #6580
I seriously considered `if (regexPart === '$') {` since patterns like `/x$/` work better without the workaround (matches on last line).
I've opted to remove the useless calls to replace. Works fine as is and the flags ought to be saved, though they aren't currently.

[vim] substitute pattern ending in dollar

---

keymap/vim.js

A simple one :)
Fixes the issue reported on the forum https://discuss.codemirror.net/t/vim-incorrect-behavior-of-key-shift-key-in-ubuntu-20-04/2811
Adding CapsLock to `modifiers` means that `cmKeyToVimKey` won't treat it as a character (see `hasCharacter`). No other references to `modifiers`.

[vim] ignore CapsLock key events

---

doc/manual.html
src/model/Doc.js

This PR sets the default `head` to `anchor` in `setSelections()`, similar to `setSelection()`.
I think it should have been this way to ensure the API is consistent.
I'm more concerned about someone reading the latest docs but using an older version of CM that doesn't support this. Not sure how this is dealt with generally.

Allow the omission of head in setSelections

---

mode/lua/lua.js

It's inconvenient to have to manually dedent lines after typing `end` or `else`.  Note that `elseif` is also covered by this pattern, as `else` is a prefix of it.

[lua mode] use electricInput to automatically dedent

---

src/input/keymap.js

Fixes https://github.com/codemirror/CodeMirror/issues/6630
Removes `Alt-D`, `Alt-F` and `Alt-B` from the default `emacsy` key bindings, which is enabled by default on macOS.
> A PR that moves those from `emacsy` to the proper emacs map in `keymap/emacs.js` would be very welcome.
It seems like these three are already implemented in `keymap/emacs.js`
https://github.com/codemirror/CodeMirror/blob/8bc57f76383e62e1a03c7d97c9eac74493fdbedc/keymap/emacs.js#L309
https://github.com/codemirror/CodeMirror/blob/8bc57f76383e62e1a03c7d97c9eac74493fdbedc/keymap/emacs.js#L311

Remove option-based emacsy key bindings

---

addon/hint/show-hint.js
addon/tern/tern.js

Tooltips and the scrollbar inside the hint container can be off screen, which can induce scrollbars on the document body.
Only related bug I could find:
Fix: #5622

Fix: Tooltips can be off screen

---

addon/runmode/runmode.js

Without the mode object, it's not possible to call the mode's `indent` method to compute how much a given line should be indented (which we now have a need to do in a standalone way).

[runmode] Pass the mode object to the callback

---

mode/r/r.js

The rule for starting a variable name is:
> A syntactically valid name consists of letters, numbers and the dot or underline characters and **starts with a letter or the dot not followed by a number**.
Per https://stat.ethz.ch/R-manual/R-devel/library/base/html/make.names.html
"dot not followed by a number" is handled by parsing numerics earlier

remove extra test by restricting \w to exclude _ and 0-9

---

mode/r/r.js

See https://stat.ethz.ch/R-manual/R-devel/library/base/html/dots.html and https://stat.ethz.ch/R-manual/R-devel/library/base/html/Reserved.html
Currently CodeMirror treats things like `..1.` and `...1` identically to `...`, `..1`, `..2`, etc.
The former two parse, but they parse as regular R objects per the naming rules seen e.g. here https://stat.ethz.ch/R-manual/R-devel/library/base/html/make.names.html
> A syntactically valid name consists of letters, numbers and the dot or underline characters and starts with a letter or the dot not followed by a number. Names such as ".2way" are not valid, and neither are the reserved words.
Please LMK if this should be tested, with the caveat that this is my first ever contribution to JS code so some hand-holding would be nice

tweak to regex for dots in R

---

src/input/ContentEditableInput.js

Fixes bug where the cursor always jumps back to the first character of the line after each key input. This happens when using `contenteditable` mode within a shadow root.
https://jsbin.com/jujuxux/edit?html,output
CM5's `contenteditable` mode uses `document.activeElement` to access the current focus state of the editor and put the cursor in the correct place after an edit. However, when the input element is located within a [shadow root](https://developer.mozilla.org/en-US/docs/Web/API/ShadowRoot), then `document.activeElement` is not the focused editor element itself, instead it is the host element in the document scope that *contains* the focused editor element. This causes some confusion that ends up placing the cursor back on the start of the line after each edit.
This PR replaces use …

Fix shadow root contenteditable cursor edit bug

---

src/display/update_line.js

Prevent line numbers from being voiced by screen readers.
Sets `aria-hidden=true` on `.CodeMirror-gutter-wrapper` elements.
Tested with Voice Over on Chrome.
Fixes #6578

Prevent line numbers from being voiced by screen readers

---

src/addon/runmode/codemirror-standalone.js

This is needed e.g. for the google-modes to produce correct indentation.

[runmode] Export countColumn on the minimal CodeMirror

---

src/display/update_display.js

Some consumers need to know when the gutter width changes.  For
example, the MediaWiki Visual Editor maintains a transparent overlay
that must line up with the CodeMirror text area.  When line numbering
is enabled, the gutter will automatically resize as content grows
beyond 1,000 lines (and 10,000, etc.).  This shifts the text area,
and we need to recalculate position using
`display.gutters.offsetWidth`.

Send new "updateGutter" signal on gutter resize

---

keymap/emacs.js

This change is related to the change in [this commit](https://github.com/codemirror/CodeMirror/commit/1951460e52e2ec1d3615b5240123fe3c284d2e17) and discussed in #5020, except for emacs instead of sublime. It simply exposes the functionality that lived in anonymous functions behind commands that are named according to their corresponding emacs functions (except where they conflict with other commands). No logic was changed - just moved around.

Expose emacs commands for easier programmatic access

---

mode/velocity/velocity.js

The exclamation point at the start of a variable makes it 'silent' (it's wont be printed in case it is null)
See: http://velocity.apache.org/engine/devel/vtl-reference.html#variables

Allow an exclamation point at start of variable

---

demo/theme.html
theme/abbott.css

I've ported the [abbott.vim color scheme](https://github.com/bcat/abbott.vim) (version 2.1) to a CodeMirror theme. It's as faithful a port as I could reasonably make given that CodeMirror's syntax highlighting tokens don't perfectly map onto Vim's highlight groups.
I saw the note in the pull request template to not submit a PR for a new mode or addon. I wasn't sure if the same applied to themes, so if y'all aren't merging new themes upstream either, please just let me know. Thanks! :)

Add initial port of abbott.vim v2.1 theme

---

theme/abbott.css

I'm sorry, it seems there's a syntax error in the theme that was merged in PR #6677. Just sending a quick fix for that. (I didn't catch this previously because I only tested the theme in browsers that also support the standard `::selection` pseudoelement, so the broken `::-moz-selection` rule didn't cause any visible issues.)
I ran abbott.css through the CSS validator to check for any more errors, and it validates successfully after this change.

[abbott.vim theme] Fix -moz-selection syntax error

---

mode/crystal/crystal.js

Fixed #6675
Note that the last one `5%a` is not fixed, because it is hard. Please see https://github.com/codemirror/CodeMirror/issues/6675#issuecomment-835658444.
Thank you.

Fix `%` highlight in Crystal

---

mode/javascript/javascript.js

Syntax highlighting of TypeScript broke after encountering the first exclamation mark (Non-Null Assertion Operator).
Before:
After:

Fixes the syntax highlighting of TypeScript that broke after the exclamation mark

---

demo/mustache.html

fix a documentation link to point to new mustache documentation URL replacing `mustache.github.io` instead of `mustache.github.com` (which return a 404 as of today).

fix link from the documentation pointing to old mustache doc url

---

addon/lint/lint.js

Over on https://github.com/Kong/insomnia/, we've been getting this error on codemirror.  It appears to be (ultimately) due to a missing check for `state.lint` being present.  Sometimes it's there, sometimes it isn't.
This PR fixes this bug.

fix: [lint] exits early if required state is not present

---

src/model/Doc.js

Currently `getRange(a,b,'')` works the same as `getRange(a,b)`.

make getRange(a,b,'') work as expected

---

addon/lint/lint.css
addon/lint/lint.js

When linter shows errors, there is no way to highlight the whole row
I'm able to set icon only
I would like to have a possibility to highlight the whole row, like:

feat: Highlight a row when lint caused error

---

addon/lint/lint.css
addon/lint/lint.js

There is alway "red" lines for linter even "warning" message:
Expected result:

bugfix: highlight line by severity code

---

doc/manual.html

This is important when using `=>`:
```js
editor.eachLine(line => editor.removeLineClass(line, "wrap"));   // doesn't work as expected
editor.eachLine(line => {editor.removeLineClass(line, "wrap")}); // works as expected
```

augment eachLine doc

---

mode/soy/soy.js
mode/soy/test.js

Add support to soy for:
{const FOO = 5 /}
{export const FOO = 5 /}

[soy mode] Add support for const and export const.

---

AUTHORS
keymap/vim.js

https://github.com/codemirror/CodeMirror/issues/6660
Created a regex that will match  all uppercase ascii/cyrillic characters. This will improve the accuracy of function isUpperCase() and allow vim shortcut "shift + ~" to convert lowerCaseChars => upperCaseChars & upperCaseChars => lowerCaseChars on cyrillic characters.

Fix #6660. Created regex to match all uppercase ascii/cyrillic chars

---

mode/clike/clike.js

https://github.com/codemirror/CodeMirror/issues/6545
Added the 'var' keyword to the "text/java" types word string. var keyword is now highlighted in the same way 'int' is currently.
Can place 'var' in another section eg. keywords: words('var') etc if you would rather 'var' match other elements. thanks

Highlighted 'var' keyword in Java

---

mode/python/python.js

Added `rb` and `rf` to python highlighter.
Only added to python 3 because there's no f-string in python2.
Now we support all python string prefix. See : https://docs.python.org/3/reference/lexical_analysis.html#string-and-bytes-literals
fixes #6727

Add python 3 string prefix `rb` and `rf`

---

addon/fold/foldcode.js

A couple of perforance improvements for the fold code addon
For the `foldAll` and `unfoldAll` commands, the fold addon already iterates through every line in the file, so a secondary loop upward, for every line, is wasteful.
For the `unfold` command, `doFold` exits after `getRange` anyway, and depends on the marker clearing side effect in `getRange` for unfolding. When scanning up, these ranges are not unfolded anyway because of the `allowFolded` check, so having scanUp enabled just causes a bunch of extra `findMarksAt` calls for no reason.
`getRange` iterates over all marks at a position and then checks for `force === "fold"` at each loop iteration. This change exits before the loop instead, saving the call to `getMarksAt` and the iteration.

Improve folding addon performance

---

src/display/Display.js
test/test.js

I think don't need to translate programming code.
ref https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/translate

set attribute [translate="no"]

---

addon/merge/merge.js

When the merge editor is used with VoiceOver utility, it is not possible to use "Revert chuck" and "Toggle locked scrolling" buttons with keyboard. With this change, it will be possible.

Allow merge editor buttons to be used with keyboard

---

src/display/selection.js

This pull request should fix https://github.com/codemirror/CodeMirror/issues/3256
(non monospace font and header size is different from other portion of a text)
I don't think it's good idea to check if vim mode is enabled directly in `cursorCoords` but I don't really see the better way. 
Could somebody help me with better solution? 
Thanks

[vim] fix fat cursor for non-monospace fonts

---

keymap/emacs.js

Commit https://github.com/codemirror/CodeMirror/commit/97ee57515599e95972567c41ed9176ddfb1f4fb9 changed the baviour of Ctrl-V and Alt-V and I believe this was unintentional.
Previously, it was set to
```
"Alt-V": move(byPage, -1), "Ctrl-V": move(byPage, 1),
"PageUp": move(byPage, -1), "PageDown": move(byPage, 1),
```
So Alt-V and PageUp were the same command and Ctrl-V and PageDown likewise.
I think this is the correct behaviour and is as is described here: https://www.gnu.org/software/emacs/manual/html_node/emacs/Scrolling.html
This PR updates it accordingly.
I have set scrollUpCommand to move forward by 1 page, inverting the functionality of that command as that is close to how the command is described in the emacs docs. (And likewise with scrollDownCommand.)

Fix emacs scroll-up / scroll-down bindings

---

src/display/selection.js

In particular the fat cursor would be invisible on empty lines.

Fix 0-width fat cursor at EOL

---

theme/solarized.css

The text drop shadow unnecessarily makes text slightly blurry.

Remove text-shadow from solarized theme.

---

keymap/vim.js
test/vim_test.js

For multikey operators gu, gU, gq repeating the last key must act the same way as repeating the whole operator.

[vim] add support for guu

---

mode/soy/soy.js

Fix, or at least reduce, some issues where keywords are matched in the wrong place.
- `record` should only match as part of `record(foo: 1, bar: 2)`.
- `map` should only match as part of `map("foo": 1, "bar": 2)`.
- `import`, `from` and `as` in the statement `import {foo as bar} from 'my.import';`

Fix bad matches of map, record, from, as, import.

---

mode/scheme/scheme.js

This PR fixes #6822 and handling of escaped symbols, I've reused handling of strings so escape inside symbols works the same.
Here is an example of how this works, the code for the mode is the same (it includes my modifications, but the added code is exactly the same)
https://codepen.io/jcubic/pen/qBXwGaV

fix handling of escaped symbols in Scheme mode #6822

---

mode/nsis/nsis.js

NSIS variables are actually allowed to contain a `.`-character unless it's at the start of the variable name. See [example](https://github.com/kichik/nsis/blob/master/Contrib/Modern%20UI%202/Interface.nsh#L11-L25).

[nsis mode] fix variable pattern

---

mode/nsis/nsis.js

NSIS definitions can contain `!`-characters, as you can see on the [NSIS wiki](https://nsis.sourceforge.io/Check_if_a_file_exists_at_compile_time) (note the `!define !defineifexist` part)

[nsis mode] fix defines pattern

---

mode/nsis/nsis.js

Basically the same as #6838, but for language strings. Unfortunately, I cannot provide any examples to back this up.

[nsis mode] fix language strings pattern

---

mode/nsis/nsis.js

Follow-up to #6837 to support single-letter variable names

[nsis mode] improve variable pattern

---

mode/factor/factor.js

Removed redundant line comment symbol from Factor language mode, fixing #6844 .

Fixed incorrect lineComment (#6844)

---

mode/nsis/nsis.js

All NSIS syntax is actually case-insensitive , this PR adds support for that. I wish I could provide a link that proofs this, but this is not mentioned in the NSIS documentation or wiki. Given my history with this mode, I hope you can trust me anyway!

[nsis] allow case-insensitive syntax

---

mode/htmlmixed/htmlmixed.js

The htmlmixed mode's `getTagRegexp()` function composes a regex out of double-quoted strings, which contain the `\s` regex character specifier. However, this is first being interpreted as a string escape code, which ends up being equivalent to `/<\/s*/` (zero or more instances of the 's' character) instead of the intended `/<\/\s*/` (zero or more instances of any whitespace character).
This pull request fixes the escaping to be consistent with that used in the `getAttrRegexp()` function a few lines above.

[htmlmixed mode] Fixed escaping in double-quote regex string

---

keymap/vim.js
test/vim_test.js

Resolves  #6234 
This change only affects normal mode. It's still possible to map <Esc> in insert and visual mode, and it will be ignored in favour of the default action of exiting to normal mode.

Allow mapping <Esc> in vim normal mode

---

addon/edit/continuelist.js

Check both inner.mode.name and inner.mode.helperType for "markdown".

[addon/edit/continuelist] Check mode.name AND helperType for "markdown"

---

mode/clike/clike.js

For #6873
Before the fix:
After the fix:

Fix Java textblock syntax

---

src/input/input.js

I noticed that when the border of the CodeMirror component is clicked but the editor has not received the blinking cursor, that the paste operation can still happen.
Reproduce in master:
This can be seen by copying some text, click the border of the CodeMirror editor exactly (e.g., at https://codemirror.net/demo/html5complete.html), and paste using the system keyboard shortcut. The pasted text appears in the editor without a blinking cursor.

fix the paste operation when the cell is unfocused

---

addon/comment/comment.js
test/comment_test.js

Currently, when you comment the first line of an empty function you lose the indent.
This PR has a simple fix that means commenting an indented empty line will keep the indent.

Preserve whitespace when commenting

---

addon/search/search.js
src/input/input.js

Minor change made for the project to be a bit more accessible ('label' violation)

Minor changes to make CodeMirror accessible (label and color-contrast)

---

addon/hint/show-hint.js

We have to prevent to render the hint tooltip popup to far to the left, which exceeds the viewport.
If it exceeds the viewport too much to the left, we fallback to zero position.

Fix, don't exceed viewport for hint tooltip

---

mode/swift/swift.js

[Closes #6937]
* Added `actor`, `isolated`, `nonisolated`, `async`, and `await` to `keywords`
* Added `actor` to `definingKeywords`

[#6937] Support for Structured Concurrency in Swift

---

mode/sparql/sparql.js

This is an apparently overlooked keyword that only appears in LOAD commands.
See "Grammar" line 31 in
https://www.w3.org/TR/sparql11-query/

Add INTO keyword to SPARQL mode

---

mode/css/css.js

The character class `[A-f]` is equivalent to the character class `[A-Z\[\\\]^_`a-f]`, which I don't think is what you meant to put there.  
You call see the bug if you e.g. go to the [CSS demo page](https://codemirror.net/5/mode/css/) and try "colors" such as `#ZZZ` or `#_X_` and see that they are highlighted as a valid color.  
But e.g. `#xyz` is not highlighted as a valid color.  
I'm making a CodeQL query to identify such mistakes, and that's how I found this bug.  
You can see the WIP query here: https://lgtm.com/query/3452833904737970282/

fix the char ranges identifying valid colors in CSS

---

keymap/vim.js
test/vim_test.js

This PR adds support for the text object operations using the sentence operator (`vis`/`vas`/`dis`/`das`/`cis`/`cas`/`yis`/`yas`).
I've also added tests, they all pass.
This is intended to be added to the cm6 vim repo eventually.
https://github.com/replit/codemirror-vim/pull/19
Closes #5454.

add sentence option for around/inner text object operation

---

mode/go/go.js

Go 1.18 introduced two new predeclared identifiers: `any` and `comparable`:
https://go.dev/doc/go1.18#generics

[go mode] Add new builtin types `any` and `comparable`

---

mode/elm/elm.js

This lets a user toggle comments with a keyboard shortcut when using codemirror to edit Elm code.

Add support for line comments to the Elm mode

---

addon/tern/tern.js

This addresses a potential XSS vulnerability caused by tern's
construction of inline HTML where text input is not escaped, which is
then passed to the openDialog function for rendering. The construction
is replaced with an equivalent DOM fragment construction, which
the openDialog API also supports.
This is currently a blocker for CodeMirror users that want to enforce
Trusted Types in their web application.

[security] Ensure text in tern dialog is escaped

---

addon/runmode/colorize.js
addon/runmode/runmode.js

In general, assigning a plain string to the innerHTML property of an
element can cause XSS vulnerabilities, and is thus considered as a
violation by the [Trusted Types](https://web.dev/trusted-types/) web platform security mechanism. This
PR addresses two such violations in CodeMirror by replacing them
with semantically equivalent assignments to the textContent property.
This is currently a blocker for CodeMirror users that want to enforce
Trusted Types in their web application.

[security] Use textContent instead of innerHTML

---

src/edit/mouse_events.js

Text selection was broken in the latest commit because the `extend` function is defined within the `leftMouseSelect` function and that caused `doc()` the function to be shadowned by `doc = cm.doc` the local variable.

Fix for new function name clashing with local variable.

---

mode/sparql/sparql.js

SPARQL specifies prefixes, for example "bio" in the prefix specification below, according to https://www.w3.org/TR/sparql11-query/ Productions for terminals [168]
`PREFIX bio: <http://purl.org/vocab/bio/0.1/>`
sparql.js has a simple last-chance regular expression that is used to match prefixes, operators and keywords. This does not, for example, allow hyphen and period characters in prefixes despite them being permitted (in different places) according to the specification. This has been augmented with the patterns from the specification to identify prefix atoms before the operators and keywords are processed as before.
Note that the mode continues to treat anything after a prefix as being a PN_LOCAL (Productions for terminals [169]). This is correct in the places within a SPARQL statement …

[sparql mode] Identify all characters in prefixes

---

src/input/input.js

Fixes https://github.com/codemirror/codemirror5/issues/7009 and ultimately should fix https://github.com/directus/directus/issues/16690.

Use autocorrect and autocapitalize value of on instead of empty string

---

addon/merge/merge.js

The merge editor's buttons are not accessible through spacebar. Making the change to make them interactive with spacebar also.

Accessibility - add keyboard spacebar interactive for merge editor buttons

---

mode/nsis/nsis.js

- adds `!assert` command, as introduced by NSIS v3.09 (see [changelog](https://nsis.sourceforge.io/Docs/AppendixF.html#v3.09))

add !assert command

---

mode/dart/dart.js

The [inline classes feature](https://github.com/dart-lang/language/blob/main/working/1426-extension-types/feature-specification-inline-classes.md) this was part of is now obsolete and will not be part of the language. It will likely be replaced by [extension types](https://github.com/dart-lang/language/blob/main/accepted/future-releases/extension-types/feature-specification.md).

Remove support for inline keyword in Dart mode

---

.github/workflows/ci.yml

Resolves https://github.com/codemirror/codemirror5/issues/7064
It's important to make sure the SHA's are from the original repositories and not forks. I have manually verified all of them and added references in the commit description.

Reference actions by commit SHA

---

src/display/operations.js
src/display/update_display.js
src/edit/fromTextArea.js
src/edit/key_events.js
src/edit/methods.js
src/edit/mouse_events.js
src/input/ContentEditableInput.js
src/input/TextareaInput.js
src/util/dom.js

Ref https://github.com/codemirror/codemirror5/issues/7074
This change should be:
- noop for old <2017 browsers
- noop for modern browsers when codemirror is in the document or in the open shadow root
- should be fixing input (focus, pasting) when codemirror is in the closed shadow root
The problem was that we were going from element to ownerDocument and then descending. And closer roots can only be pierced one way. The solution is to not climb to the ownerDocument, but stop at the local root node (nearest shadow root).
Works on Safari.

[shadow dom] make codemirror work inside closed shadow root

---

mode/clojure/clojure.js

Clojure can use 'brace' to fold code

feat: use 'brace' fold on clojure code

---

mode/dart/dart.js

Dart is [adding support for digit separators](https://github.com/dart-lang/language/blob/main/working/digit-separators/feature-specification.md), the underscore, like `1_000_000` or `0x33_33_33`. The Dart playground, [DartPad](https://dartpad.dev/), still runs on codemirror5, so this would be a welcome fix.

Dart: support digit separators

---

mode/gherkin/gherkin.js

In this update, I extended the CodeMirror syntax highlighting to include two additional Gherkin keywords: Rule and Example. These keywords are now recognized in several languages, including Arabic, Hebrew, and more.
Why this change was made:
The previous implementation did not support the Rule and Example keywords, which are crucial for structuring Gherkin feature files. By adding these keywords with multilingual support, the change enhances the experience of writing Gherkin feature files in various languages, improving readability and accuracy for users working with Gherkin-based testing.

Added support for two important keywords: 'Rule' and 'Example'.

---

demo/theme.html

Mild bug in demo due to space handling.
Before: https://codemirror.net/5/demo/theme.html#solarized%20dark
1. dropdown .value set to non-existant `solarized%20dark` => dropdown reset to blank.
2. picking solarized dark / light from dropdown changes theme ([correctly](https://codemirror.net/doc/manual.html#option_theme) sets `.cm-s-solarized .cm-s-dark` classes),   
sets URL fragment to `#solarized%20dark` (implicitly encoded by browser?¹),  
which again triggers dropdown reset to blank (1).
3. can't iterate all dropdown values by Down/Up arrow: once you reach solarized, (2) happens
After: https://raw.githack.com/cben/CodeMirror5/theme-demo-location-hash-DEBUG/demo/theme.html#solarized%20dark (from [debug branch](https://github.com/cben/CodeMirror5/commits/theme-demo-location-hash-DEBUG/) …

[theme demo] Fix dropdown losing choice on solarized light / dark

---

src/display/Display.js

In Chrome 105 due to a bug, `clip-path` needed to be set as pointer events were ineffective outside CodeMirror editor instance but within paddings and margins of its elements. This has been resolved in Chrome 106 as seen [here](https://issues.chromium.org/issues/40863245#comment21).

clip-path issue fixed in Chrome 106

---

mode/clike/clike.js

From the [Kotlin Spec](https://kotlinlang.org/spec/pdf/kotlin-spec.pdf) section _1.2.3 Literals_ there are only 3 Rules that define suffixes for literals:
```ebnf
FloatLiteral:
DoubleLiteral ('f' |'F')
| DecDigits ('f' |'F')
UnsignedLiteral
(IntegerLiteral | HexLiteral | BinLiteral) ('u' |'U') ['L']
LongLiteral
(IntegerLiteral | HexLiteral | BinLiteral)'L'
```
Ignoring casesensitivity we can catch them all with the regex `(ul?|l|f)` however the current regex for Kotlin suffixes looks like `(u|ll?|l|f)` which leads to the following inconsistency:
```kotlin
// Correctly highlighted by Codemirror and valid Kotlin
val a = 13u
val b = 24l
// Incorrectly highlighted by Codemirror but valid Kotlin
val c = 26UL
// Highlighted as one number but invalid Kotlin
val d = 72ll
```

[kotlin mode]: Fix unsigned long literal token
