test/lint.js

See #4259 and marijnh/blint#2. Does not pass for me.

Disallow semicolons in src/

---

mode/julia/julia.js

[julia mode] Fixes for julia 0.5

---

src/edit/options.js

Add U+061C Arabic Letter Mark to special chars

---

src/display/scrollbars.js
src/display/update_display.js
src/input/ContentEditableInput.js
src/input/TextareaInput.js
src/util/misc.js

Needs `buble@0.15.1`, but `buble-rollup-plugin@0.15.0` can pull that in.

Convert some classes to ES6

---

mode/css/css.js

See: https://drafts.csswg.org/css-grid/#grid-shorthand

[css mode] Add "auto-flow" value for grid property

---

mode/soy/soy.js

[soy mode] Add missing `\b`s to keyword regex

---

mode/javascript/test.js

[javascript mode] add tests for async keyword

---

mode/go/go.js

Reference: https://golang.org/pkg/builtin/#rune

[go mode] Added missing keyword 'rune'

---

src/input/movement.js
src/measurement/position_measurement.js
test/test.js

This adds to #4539, so please review that first.

Use wrappedLineExtent in moveVisually

---

addon/fold/xml-fold.js

Add tag parameter to xml-fold findEnclosingTag to find enclosing tag of particular type.

Add tag parameter to xml-fold findEnclosingTag

---

mode/julia/julia.js

[julia mode] Properly handling of string literals

---

mode/soy/soy.js
mode/soy/test.js

[soy mode] Support single-quoted strings in tags

---

src/measurement/position_measurement.js

This closes #4691 and is based on an idea by Joel <joel.einbinder@gmail.com> (see #4692).

Faster coordsChar for bidi content

---

mode/clike/clike.js

Enums are available in Dotty and soon will be available in Scala.

[scala mode] Add enum

---

mode/julia/julia.js

This is an update to properly handle some syntax changes from Julia 0.6 (also includes some other fixes).

[julia mode] Julia 0.6 syntax updates

---

.editorconfig
.gitattributes

closes https://github.com/codemirror/CodeMirror/issues/4849

add .editorconfig

---

mode/gfm/index.html

Tiny update of gfm doc to reflect latest emoji change.

[gfm mode] update doc

---

CHANGELOG.md

- before: http://codemirror.net/mode/demo/vim.html
- after: http://codemirror.net/demo/vim.html

Fix broken links

---

demo/bidi.html
lib/codemirror.css

Fix for bug https://github.com/codemirror/CodeMirror/issues/4897

Fix(bidi): Fix for bug /codemirror/CodeMirror/issues/4897

---

mode/soy/soy.js

Reference: https://developers.google.com/closure/templates/docs/concepts#injecteddata

[soy mode] Support injected data

---

addon/mode/simple.js
demo/simplemode.html

Closes #4970. Even if you beat me to it I still like my commit better :P And I have arguments: It also works with `token: null` and fixes the documentation.

[mode/simple addon] Allow capturing with single tokens

---

README.md

Mentioned CodeMirror's great ability to highlight code in the README. This tells users about the syntax highlighting - which isn't mentioned much elsewhere in the README.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/codemirror/codemirror/4979)

Emphasised on highlighting

---

test/vim_test.js

Added test for #4985.
Took time to figure out how to test this :).

[vim binding] test for ctrl-w in insert mode

---

doc/realworld.html

Adding [Codiva.io Online Java Compiler and IDE](https://www.codiva.io) to the existing users list.
This will highlight some of the advanced usage of CodeMirror
- Multiple Tabbed editor
- Continuous compilation in the backend
- Autocompletion
- Mobile friendly
- Read-only mode

Add Codiva.io to realworld usage list

---

doc/realworld.html

Removing the broken links in the realworld users list. I checked the backlinks using,
https://www.deadlinkchecker.com/website-dead-link-checker.asp
and manually verified these urls to be invalid.

Remove broken links in the realworld users page

---

mode/soy/soy.js

Soy supports comments in all contexts but CodeMirror parses them only outside tags. This adds the support to the tags too.

[soy mode] Support comments in all contexts

---

mode/javascript/javascript.js
mode/javascript/test.js

[javascript mode] Highlight type in generic call

---

mode/clike/clike.js

This kotlin keywords will be added in 1.2 version of Kotlin.

Add new kotlin keywords.

---

addon/lint/javascript-lint.js

see https://github.com/codemirror/CodeMirror/pull/5184#issuecomment-358267454

[javascript-lint addon] Removed error code and message overrides

---

addon/lint/javascript-lint.js

When using tabs for indentation, the markers would not always align with the actual problem.
The old workaround for JSHint never really worked (only when a line had one tab) and I found a simple option which fixes the issue.
This time I also checked backwards compatibility, which works even fine with the old JSHint version R07.
As a second marker fix, I added an error line check, since JSHint for some reason adds configuration issues in the errors array with line: 0, character: 0. Now, if you pass an invalid option you will get a console error instead of an invisible marker.

[javascript-lint addon] Fix error markers

---

mode/dockerfile/dockerfile.js
mode/dockerfile/test.js
test/index.html

add more instructions
highlight instructions as 'keyword'
highlight 'from ... as'
add tests

[Dockerfile mode] Some improvements

---

mode/dockerfile/dockerfile.js
mode/dockerfile/test.js

- highlight strings
- highlight ports as numbers in expose instruction
- highlight comments as such only when they appear at the start of a line
- consider also ` as a line continuation

[Dockerfile mode] Highlight strings and ports

---

keymap/vim.js
test/vim_test.js

http://vim.wikia.com/wiki/Alternate_delimiters_for_the_replace_command

[vim] add support for alternate delimiters for the replace command

---

doc/manual.html

fix doc-manaual.html dom tag

---

mode/markdown/markdown.js

[markdown mode] detecting xml mode inside markdown

---

addon/edit/continuelist.js

This PR will fix the bug #5290.
I'd appreciate it if you decide to merge to master branch.
regards.
```
CodeMirror>npm run test --scripts-prepend-node-path
> codemirror@5.35.1 test CodeMirror
> node ./test/run.js
All passed
```
I'd checked in demo. (Using CodeMirror/mode/markdown/index.html)

fixed list numbering error. (#5290)

---

keymap/vim.js

I created this pull requect for issue #5334

Fix argument of scanForBracket method call issue#5334

---

keymap/vim.js

See https://github.com/codemirror/CodeMirror/issues/5299#issuecomment-377352040.

[vim] Don't insert chars if key is not bound

---

doc/realworld.html

I've added _salvare_ to `doc/realworld.html`.

[real-world uses] Add salvare

---

theme/darcula.css

[themes] update `darcula` matchingbracket

---

addon/display/panel.js

See description of issue here:
https://github.com/codemirror/CodeMirror/issues/5518

Fix for issue 5518

---

mode/clojure/clojure.js

This provides default `hintWords` when auto-completing in Clojure code.

[clojure mode] Provide `hintWords`

---

mode/julia/julia.js

This provides default `hintWords` when auto-completing in Julia code.

[julia mode] Provide `hintWords`

---

mode/shell/shell.js

This provides default `hintWords` when auto-completing in Shell code.

[shell mode] Provide `hintWords`

---

mode/r/r.js

This provides default `hintWords` when auto-completing in R code.

[r mode] Provide `hintWords`

---

mode/dart/dart.js

- add the `mixin` keyword to the Dart mode

add the mixin keyword to the Dart mode

---

mode/clojure/clojure.js
mode/clojure/index.html
mode/clojure/test.js

I refactored the entire Clojure mode based on the Common Lisp mode so that it's now much easier to reason about thanks to the separation of concerns (styling and indentation). As part of this PR, I also polished the example code so that its code style is up to date.

[clojure mode] The Grand Refactoring of the Clojure Mode

---

mode/clojure/clojure.js
mode/clojure/test.js

This PR partially resolves issues #1896 and #2314.

[clojure mode] Highlight forms wrapped by `(comment ...)` as `comment`.

---

theme/gruvbox-dark.css

The colors were off for certain words in C++ and Java so this is to correct those mistakes.

Update gruvbox-dark colors

---

mode/css/css.js

Closes #5625
Inserted the property in the existing list, considering alphabetical order.

Add mix-blend-mode CSS property

---

mode/clike/index.html

Shows off some newer Objective C features and makes "visual" testing new features easier.

[clike mode] Add a better Objective C demo

---

mode/meta.js

Added "f95" to Fortran extensions.

Add "f95" to list of extensions for Fortran mode.

---

mode/soy/soy.js
mode/soy/test.js

- highlighted the namespace itself as a variable. This is
in line with how Java packages are highlighted.  I believe
this is a close approximation.
- added 2 tests to verify new highlighting.

soy namespace name highlighting

---

mode/soy/soy.js
mode/soy/test.js

- added tokenization for soy function names. Assigned to variable & callee
- added tests to verify it works within expressions

[soy mode] tokenize soy functions

---

mode/soy/soy.js
mode/soy/test.js

Currently this type is not being highlighted.
- added token "type" for ?
- added test for single type
- added test for ? as a template type parameter

[soy mode] added token for unknown type "?"

---

mode/soy/soy.js
mode/soy/test.js

- tokenize arithmetic and equality operators as "operator"
- added tests to validate this

[soy mode] tokenize operators in expressions

---

mode/soy/soy.js
mode/soy/test.js

- added null as atom
- added null coalescing as operator
- changed [=] to = in operator regex
- added tests to validate new highlighting

[soy mode] added null literal and null coalescing operator

---

addon/hint/html-hint.js
doc/manual.html
src/edit/options.js
src/input/ContentEditableInput.js
src/input/input.js

Would like the ability to enable autocorrect and autocapitalize in addition to spellcheck. Verified that the same tests pass that pass on master.

Add options for autocorrect, autocapitalize

---

mode/jinja2/jinja2.js
mode/meta.js

In this PR, I'm simply setting the MIME for the Jinja2 language to "text/jinja2".
See #5709 for my previous PR on this topic.
Thanks in advance.

Updating MIME type of Jinja2 to "text/jinja2"

---

doc/realworld.html

Colon is a text editor, built on Electron using CodeMirror, it has most of the features of text editors and it also has capability of executing the programs of different - different programming languages, it is mainly very useful for coders, they work on different - different programming languages and don't want to install different - different IDE's
Repo : https://github.com/Chhekur/colon-ide
Website : https://chhekur.github.io/colon-ide
Releases: https://github.com/Chhekur/colon-ide/releases

[real-world uses] Add Colon

---

addon/edit/continuelist.js

Fix for issue #5757. It works for my purposes but I haven't tested it super thoroughly, is there a test suite where it should go?

Make newlineAndIndentContinueMarkdownList understand inner modes

---

mode/julia/julia.js

[julia mode] Fix some indentation issues

---

mode/soy/soy.js

The name change was made in Soy recently.

[soy mode] Update @prop to @state.

---

demo/theme.html
theme/nord.css

I've added a new theme based on https://github.com/arcticicestudio/nord

added nord theme

---

addon/edit/closebrackets.js

Resolves #5512 
Improves the current behavior which auto closes every opening bracket. Improved behaviors are observed from VSCode.
- hardcodes a shuoldClose list of characters that if the next character is in the list, opening a bracket should be auto-closed.
The list is : ")]}'\":;>"
Basically the closing characters in pairs  ; : and >.
- when opening a bracket, it will be auto-closed if:
1. there is no next character,
2. the next character is a white space character.
3. the next character is in the shouldClose list.

Improves closebrakcets

---

addon/hint/sql-hint.js
test/sql-hint-test.js

- [sql-hint addon] Add tests for defaultTable and disableKeywords
- [sql-hint addon] Fix #5817

[sql-hint addon] Add tests and fix #5817

---

theme/yonce.css

I spent a fair bit of time actually coding with the color theme with a variety of languages and I have a few helpful tweaks. Some get the theme closer to the source material, others just make it more useful.

[yonce theme] Update colors

---

keymap/vim.js
test/vim_test.js

[vim] fix blockwise yank

---

mode/meta.js

Other places like discord, github and gitlab supports this.

"cs" alias for C#

---

mode/clike/clike.js
mode/clike/test.js

This is a change to the Java mode to resolve #5899.

Remove 'float' as Java keyword

---

doc/realworld.html

We implemented a wrapper to CodeMirror for GWT (base on JSINTEROP)

Added Coderba GWT wrapper

---

lib/codemirror.css

Fix scrolling with rulers

---

mode/clike/clike.js

Kotlin supports nested comments.
Documentation: https://kotlinlang.org/docs/reference/basic-syntax.html#comments

Support nested comments in kotlin mode

---

demo/theme.html
theme/material-darker.css
theme/material-ocean.css
theme/material-palenight.css
theme/material.css

This PR will update Material Theme syntax to match the official theme and add the new material theme variants.

Update Material Theme syntax to the official version

---

src/util/misc.js

This reduces the time the operation I mentioned in https://github.com/codemirror/CodeMirror/pull/5992 takes to ~450ms.

Reduce setTimeout/clearTimeout calls from Delayed

---

addon/hint/css-hint.js

Added new CSS Pseudo Selector from https://www.w3schools.com/cssref/css_selectors.asp

[ CSS Hint pseudoClasses] Update pseudo Classes Variable 

---

demo/theme.html
theme/ayu-dark.css
theme/ayu-mirage.css

These themes are based on https://github.com/dempfi/ayu

Adding ayu-dark and ayu-mirage themes

---

keymap/vim.js
test/index.html
test/vim_test.js

Skip folded code when moving with j/k

---

mode/cypher/cypher.js

Includes multi database and privilege management commands

Added system command keywords to Cypher

---

doc/realworld.html

Documents the use of code mirror by Adnuntius.

More real-world uses of codemirror

---

mode/soy/soy.js

Remove state.templates since it is not referenced anywhere.

Remove templates from state.

---

mode/soy/soy.js
mode/soy/test.js
src/edit/drop_events.js

What it says on the tin. There were 4 lint warnings, I have fixed them.

Fix lint warnings

---

doc/realworld.html

Using CodeMirror as HTML & CSS editors.

[real world uses] Add clone-it.github.io

---

mode/rust/rust.js

Adds a few missing keywords to the rust mode.
Reference: https://doc.rust-lang.org/reference/keywords.html

[rust] Add some keywords

---

AUTHORS
addon/hint/show-hint.js
mode/wast/index.html
mode/wast/test.js
mode/wast/wast.js
test/index.html

This adds support for WebAssembly text format, as used in the
browser DevTools (Firefox, Edge and Chrome DevTools all the like).

[wast] Add new wast mode (for WebAssembly disassembly)

---

keymap/vim.js

Disclaimer: I haven't run the linter or tests yet.

Remove a duplicate entry in defaultExCommandMap

---

src/line/highlight.js

See: https://lgtm.com/rules/1510624619946/

Proper escaping of \s

---

mode/markdown/index.html
mode/markdown/markdown.js

add fencedCodeBlockDefaultMode per https://github.com/codemirror/CodeMirror/issues/6283

add fencedCodeBlockDefaultMode

---

doc/realworld.html

Adding Adaface PairPro (remote pair programming tool with code editor, compiler and video conference) for interviews.
Added in alphabetical order.

Adding Adaface PairPro

---

keymap/vim.js
test/vim_test.js

[vim] Fix vim-mode-change event signalled twice

---

mode/pascal/pascal.js

Implements highlighting for comments with curly brackets (braces) in Pascal. See #5523.

Pascal Curl Brackets Comments

---

addon/hint/sql-hint.js
mode/sql/sql.js

it is a fix when  autocomplete hints when table name has _ $ or #.

Fix: autocomplete suggestion on _ $ and # for ODBC

---

doc/realworld.html

Request to add Innovay Web Tools (https://innovay.app/formatter/html) to the real-world uses page

Adding Innovay Web Tools to real-world uses page

---

doc/manual.html

Add events to vimAPI documentation

---

mode/soy/soy.js
mode/soy/test.js

Add support for imports, on the format:
`import {Name, Person as P} from 'examples/proto/example.proto';`

[Soy] Add support for import.

---

mode/soy/soy.js
mode/soy/test.js

Add support for using templates as param type and calling templates stored in a variable.

Soy template type

---

addon/hint/show-hint.js
doc/manual.html

To show some extra lines before and after the selected line.

[show-hint addon] Introduced option 'scrollMargin'

---

doc/realworld.html

[CodeMirror-Record](https://github.com/haoranyu/codemirror-record) supports editing activities recording and playback in CodeMirror.

[real-world uses] Add CodeMirror-Record

---

doc/realworld.html

Update realworld.html to include intervue

---

addon/hint/xml-hint.js

Fix for #6457 
I went ahead and created the PR, since I can't find an easy way to temporarily patch the published version.
Please let me know if this is an acceptable solution. Thanks!

[xml-hint addon] Replace nested function with function expression

---

mode/soy/soy.js
mode/soy/test.js

Adds support for {@attribute *} to soy mode

---

doc/realworld.html

Hello !
I would like to add [Graviton Editor](graviton.netlify.app/), it uses CodeMirror as text editor 😄 
Project repository: https://github.com/Graviton-Code-Editor/Graviton-App

[real-world uses] Add Graviton Editor

---

addon/lint/lint.js

ref: #6490
#6491 failed due The keyword 'const' is reserved (174:6) !!??
Changed to var

filter out duplicate messages 2

---

addon/search/jump-to-line.js
addon/search/search.js

Add search panel location option

---

doc/realworld.html

add MediaWiki to realworld.html

---

mode/verilog/verilog.js

This is a quick code change to improve clarity based on feedback from my previous PR #6516 .
The logic/branch is not necessary.

[Verilog mode] Remove unnecessary line.

---

mode/javascript/javascript.js

Defined the webmanifest MIME

---

doc/realworld.html

Changed SASS2CSS url

---

mode/javascript/index.html

More defined MIMEs defined by JS mode

---

doc/manual.html

Add link to demo for jump-to-line

---

doc/realworld.html

Uses CodeMirror with dynamic mode switching

[real world uses] Add coderush.xyz (typing speed test)

---

demo/closetag.html

Gave description to closetag demo

---

test/vim_test.js

This is split from https://github.com/codemirror/CodeMirror/pull/6555#issuecomment-756632741

spelling: intentionally

---

keymap/vim.js

@marijnh I missed one in #6581. 🤦

[vim] fix html in ex substitute confirm

---

keymap/vim.js
test/vim_test.js

A little bit sneaky, but does the job. If it was ES6, I'd have added a parameter with default value false.

[vim] add :vglobal ex command

---

keymap/sublime.js

Add command to sort lines in reverse order

---

mode/meta.js

"jl" alias for Julia

---

demo/theme.html
theme/juejin.css

It's the theme used in https://juejin.cn/ tech community

Add juejin theme

---

mode/soy/soy.js
mode/soy/test.js

Add support for {velog $data}{/velog} to soy.

Add velog tag

---

mode/soy/soy.js
mode/soy/test.js

Add support for {extern and {export extern.

---

mode/cobol/cobol.js

closes #6680 
**After fix:** _(line 9, 13)_

COBOL:  highlight single or double quote inside single quotes as closed string

---

mode/soy/soy.js

Add javaimpl and jsimpl as soy commands.

Add javaimpl and jsimpl as soy commands.

---

addon/search/searchcursor.js
keymap/vim.js
test/vim_test.js

searchcursor had a comment saying that skipping over empty matches is done for compatibility with vim, and vim was replacing `$` with `\n` as a workaround for the same behaviour.

[vim] remove hack for handling $ in substitute pattern

---

keymap/vim.js
test/vim_test.js

commands for go line start/end for wrapped mode were missing

[vim] implement g0 g$ g<Arrow>

---

doc/realworld.html

Tilepieces is an open source project to visually editing HTML documents and Web applications projects

added tilepieces

---

package.json

See https://github.com/codemirror/dev/issues/880

Make sure v5 patches don't override latest on npm

---

doc/realworld.html

Added [Cloud Commander](https://cloudcmd.io) to Real World.

docs: add Cloud Commander to Real World

---

mode/jinja2/index.html
mode/jinja2/jinja2.js

According to Jinja2 [template designer manual](https://jinja.palletsprojects.com/en/3.1.x/templates/#line-statements), the line statements are now supported. Test example is included.
Beside that, keyword list is slightly updated.

Jinja2 mode Line statements support

---

mode/nsis/nsis.js

Reference: https://nsis.sourceforge.io/LogicLib

[nsis mode] add ${Case} variants

---

mode/clike/clike.js

Add new C# keywords

---

mode/python/python.js
mode/python/test.js

Also, I placed True and False in the Common Keywords, b/c they belong in both versions.

Adding match/case to py3 keywords.

---

mode/python/python.js

- Aiter (added in 3.10)
- Anext (added in 3.10)
- Breakpoint (added in 3.7)

Add new python built-in functions

---

mode/dart/dart.js

new keywords are being introduced in the Dart language which should be highlighted as such:
- For the ['sealed types'](https://github.com/dart-lang/language/blob/master/working/sealed-types/feature-specification.md) language feature: `sealed`
- For the ['class modifiers'](https://github.com/dart-lang/language/blob/master/accepted/future-releases/class-modifiers/feature-specification.md) language feature: `base`, `interface`
- For the ['patterns'](https://github.com/dart-lang/language/blob/master/accepted/future-releases/0546-patterns/feature-specification.md) language feature: `when`
Related PRs and Issues:
- https://github.com/dart-lang/sdk/issues/50730
- https://github.com/highlightjs/highlight.js/pull/3726
- https://github.com/highlightjs/highlight.js/issues/3725

Add keywords to Dart mode

---

mode/dart/dart.js

Context: https://github.com/dart-lang/language/blob/master/accepted/future-releases/inline-classes/feature-specification.md
Related: https://github.com/dart-lang/sdk/issues/49734

Add `inline` keyword for Dart inline classes

---

test/comment_test.js

These tests are extracted from PR https://github.com/codemirror/codemirror5/pull/7091

Toggle Comment: Regression tests for issue #1975 and #4641

---

addon/edit/matchbrackets.js
doc/manual.html
src/display/update_lines.js

chore: remove repetitive words
